fields:
  race:
    label: "race"
    input: string
    placeholder: ""
  cosm:
    label: "cosm"
    input: string
    placeholder: "eg Core Earth, Cyberpapacy"
  ax magic:
    label: "ax magic"
    input: string
    placeholder: ""
  ax social:
    label: "ax social"
    input: string
    placeholder: ""
  ax spirit:
    label: "ax spirit"
    input: string
    placeholder: ""
  ax tech:
    label: "ax tech"
    input: string
    placeholder: ""
  clearance:
    label: "clearance"
    input: string
    placeholder: ""
  xp earned:
    label: "xp earned"
    input: string
    placeholder: ""
  xp unspent:
    label: "xp unspent"
    input: string
    placeholder: ""
  charisma:
    label: "charisma"
    input: string
    placeholder: ""
  dexterity:
    label: "dexterity"
    input: string
    placeholder: ""
  mind:
    label: "mind"
    input: string
    placeholder: ""
  spirit:
    label: "spirit"
    input: string
    placeholder: ""
  strength:
    label: "strength"
    input: string
    placeholder: ""
  movement:
    label: "movement"
    input: string
    placeholder: ""
  run:
    label: "run"
    input: string
    placeholder: ""
  toughness:
    label: "toughness"
    input: string
    placeholder: ""
  armor:
    label: "armor"
    input: string
    placeholder: ""
  dodge:
    label: "dodge"
    input: string
    placeholder: ""
  melee def:
    label: "melee def"
    input: string
    placeholder: ""
  unarmed def:
    label: "unarmed def"
    input: string
    placeholder: ""
  shock:
    label: "shock"
    input: string
    placeholder: ""
  shock tracker:
    label: "shock tracker"
    input: string
    placeholder: ""
  wounds:
    label: "wounds"
    input: string
    placeholder: ""
  wound tracker:
    label: "wound tracker"
    input: string
    placeholder: ""
  image id:
    label: "image id"
    input: string
    placeholder: "eg 12345"
  skill name 01:
    label: "skill name 01"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 01:
    label: "skill attr 01"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 01:
    label: "skill adds 01"
    input: string
  skill value 01:
    label: "skill value 01"
    input: string
  skill name 02:
    label: "skill name 02"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 02:
    label: "skill attr 02"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 02:
    label: "skill adds 02"
    input: string
  skill value 02:
    label: "skill value 02"
    input: string
  skill name 03:
    label: "skill name 03"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 03:
    label: "skill attr 03"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 03:
    label: "skill adds 03"
    input: string
  skill value 03:
    label: "skill value 03"
    input: string
  skill name 04:
    label: "skill name 04"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 04:
    label: "skill attr 04"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 04:
    label: "skill adds 04"
    input: string
  skill value 04:
    label: "skill value 04"
    input: string
  skill name 05:
    label: "skill name 05"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 05:
    label: "skill attr 05"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 05:
    label: "skill adds 05"
    input: string
  skill value 05:
    label: "skill value 05"
    input: string
  skill name 06:
    label: "skill name 06"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 06:
    label: "skill attr 06"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 06:
    label: "skill adds 06"
    input: string
  skill value 06:
    label: "skill value 06"
    input: string
  skill name 07:
    label: "skill name 07"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 07:
    label: "skill attr 07"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 07:
    label: "skill adds 07"
    input: string
  skill value 07:
    label: "skill value 07"
    input: string
  skill name 08:
    label: "skill name 08"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 08:
    label: "skill attr 08"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 08:
    label: "skill adds 08"
    input: string
  skill value 08:
    label: "skill value 08"
    input: string
  skill name 09:
    label: "skill name 09"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 09:
    label: "skill attr 09"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 09:
    label: "skill adds 09"
    input: string
  skill value 09:
    label: "skill value 09"
    input: string
  skill name 10:
    label: "skill name 10"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 10:
    label: "skill attr 10"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 10:
    label: "skill adds 10"
    input: string
  skill value 10:
    label: "skill value 10"
    input: string
  skill name 11:
    label: "skill name 11"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 11:
    label: "skill attr 11"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 11:
    label: "skill adds 11"
    input: string
  skill value 11:
    label: "skill value 11"
    input: string
  skill name 12:
    label: "skill name 12"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 12:
    label: "skill attr 12"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 12:
    label: "skill adds 12"
    input: string
  skill value 12:
    label: "skill value 12"
    input: string
  skill name 13:
    label: "skill name 13"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 13:
    label: "skill attr 13"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 13:
    label: "skill adds 13"
    input: string
  skill value 13:
    label: "skill value 13"
    input: string
  skill name 14:
    label: "skill name 14"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 14:
    label: "skill attr 14"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 14:
    label: "skill adds 14"
    input: string
  skill value 14:
    label: "skill value 14"
    input: string
  skill name 15:
    label: "skill name 15"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 15:
    label: "skill attr 15"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 15:
    label: "skill adds 15"
    input: string
  skill value 15:
    label: "skill value 15"
    input: string
  skill name 16:
    label: "skill name 16"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 16:
    label: "skill attr 16"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 16:
    label: "skill adds 16"
    input: string
  skill value 16:
    label: "skill value 16"
    input: string
  skill name 17:
    label: "skill name 17"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 17:
    label: "skill attr 17"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 17:
    label: "skill adds 17"
    input: string
  skill value 17:
    label: "skill value 17"
    input: string
  skill name 18:
    label: "skill name 18"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 18:
    label: "skill attr 18"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 18:
    label: "skill adds 18"
    input: string
  skill value 18:
    label: "skill value 18"
    input: string
  skill name 19:
    label: "skill name 19"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 19:
    label: "skill attr 19"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 19:
    label: "skill adds 19"
    input: string
  skill value 19:
    label: "skill value 19"
    input: string
  skill name 20:
    label: "skill name 20"
    input: string
    placeholder: "eg Scholar, Stealth, Survival"
  skill attr 20:
    label: "skill attr 20"
    input: select
    options:
      CHA: CHA
      DEX: DEX
      MIND: MIND
      SPIRIT: SPIRIT
      STRENGTH: STRENGTH
  skill adds 20:
    label: "skill adds 20"
    input: string
  skill value 20:
    label: "skill value 20"
    input: string
  perk name 01:
    label: "perk name 01"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 01:
    label: "perk prereq 01"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 01:
    label: "perk effect 01"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 02:
    label: "perk name 02"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 02:
    label: "perk prereq 02"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 02:
    label: "perk effect 02"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 03:
    label: "perk name 03"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 03:
    label: "perk prereq 03"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 03:
    label: "perk effect 03"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 04:
    label: "perk name 04"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 04:
    label: "perk prereq 04"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 04:
    label: "perk effect 04"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 05:
    label: "perk name 05"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 05:
    label: "perk prereq 05"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 05:
    label: "perk effect 05"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 06:
    label: "perk name 06"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 06:
    label: "perk prereq 06"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 06:
    label: "perk effect 06"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 07:
    label: "perk name 07"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 07:
    label: "perk prereq 07"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 07:
    label: "perk effect 07"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 08:
    label: "perk name 08"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 08:
    label: "perk prereq 08"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 08:
    label: "perk effect 08"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 09:
    label: "perk name 09"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 09:
    label: "perk prereq 09"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 09:
    label: "perk effect 09"
    input: text
    rows: 10
    placeholder: "description of the perk"
  perk name 10:
    label: "perk name 10"
    input: string
    placeholder: "eg Critical Strike"
  perk prereq 10:
    label: "perk prereq 10"
    input: string
    placeholder: "eg Frightening Aspect"
  perk effect 10:
    label: "perk effect 10"
    input: text
    rows: 10
    placeholder: "description of the perk"
  equipment:
    label: "equipment"
    input: text
    rows: 10
  notes:
    label: "notes"
    input: text
    rows: 10
  weapon name 01:
    label: "weapon name 01"
    input: string
    placeholder: "eg MAS Storm Shotgun"
  weapon axiom 01:
    label: "weapon axiom 01"
    input: string
    placeholder: "eg Tech"
  weapon damage 01:
    label: "weapon damage 01"
    input: string
    placeholder: "eg 15"
  weapon ammo 01:
    label: "weapon ammo 01"
    input: string
    placeholder: "eg 30"
  weapon range 01:
    label: "weapon range 01"
    input: string
    placeholder: "eg 15/30/45"
  weapon notes 01:
    label: "weapon notes 01"
    input: string
    placeholder: "eg Short Burst"
  weapon name 02:
    label: "weapon name 02"
    input: string
    placeholder: "eg MAS Storm Shotgun"
  weapon axiom 02:
    label: "weapon axiom 02"
    input: string
    placeholder: "eg Tech"
  weapon damage 02:
    label: "weapon damage 02"
    input: string
    placeholder: "eg 15"
  weapon ammo 02:
    label: "weapon ammo 02"
    input: string
    placeholder: "eg 30"
  weapon range 02:
    label: "weapon range 02"
    input: string
    placeholder: "eg 15/30/45"
  weapon notes 02:
    label: "weapon notes 02"
    input: string
    placeholder: "eg Short Burst"
  weapon name 03:
    label: "weapon name 03"
    input: string
    placeholder: "eg MAS Storm Shotgun"
  weapon axiom 03:
    label: "weapon axiom 03"
    input: string
    placeholder: "eg Tech"
  weapon damage 03:
    label: "weapon damage 03"
    input: string
    placeholder: "eg 15"
  weapon ammo 03:
    label: "weapon ammo 03"
    input: string
    placeholder: "eg 30"
  weapon range 03:
    label: "weapon range 03"
    input: string
    placeholder: "eg 15/30/45"
  weapon notes 03:
    label: "weapon notes 03"
    input: string
    placeholder: "eg Short Burst"
  weapon name 04:
    label: "weapon name 04"
    input: string
    placeholder: "eg MAS Storm Shotgun"
  weapon axiom 04:
    label: "weapon axiom 04"
    input: string
    placeholder: "eg Tech"
  weapon damage 04:
    label: "weapon damage 04"
    input: string
    placeholder: "eg 15"
  weapon ammo 04:
    label: "weapon ammo 04"
    input: string
    placeholder: "eg 30"
  weapon range 04:
    label: "weapon range 04"
    input: string
    placeholder: "eg 15/30/45"
  weapon notes 04:
    label: "weapon notes 04"
    input: string
    placeholder: "eg Short Burst"
  weapon name 05:
    label: "weapon name 05"
    input: string
    placeholder: "eg MAS Storm Shotgun"
  weapon axiom 05:
    label: "weapon axiom 05"
    input: string
    placeholder: "eg Tech"
  weapon damage 05:
    label: "weapon damage 05"
    input: string
    placeholder: "eg 15"
  weapon ammo 05:
    label: "weapon ammo 05"
    input: string
    placeholder: "eg 30"
  weapon range 05:
    label: "weapon range 05"
    input: string
    placeholder: "eg 15/30/45"
  weapon notes 05:
    label: "weapon notes 05"
    input: string
    placeholder: "eg Short Burst"
  armour name 01:
    label: "armour name 01"
    input: string
    placeholder: "eg Tactical Armor"
  armour axiom 01:
    label: "armour axiom 01"
    input: string
    placeholder: "eg Tech"
  armour adds 01:
    label: "armour adds 01"
    input: string
    placeholder: "eg +4"
  armour notes 01:
    label: "armour notes 01"
    input: string
    placeholder: "eg Min Str 8, Fatigues"
  armour name 02:
    label: "armour name 02"
    input: string
    placeholder: "eg Tactical Armor"
  armour axiom 02:
    label: "armour axiom 02"
    input: string
    placeholder: "eg Tech"
  armour adds 02:
    label: "armour adds 02"
    input: string
    placeholder: "eg +4"
  armour notes 02:
    label: "armour notes 02"
    input: string
    placeholder: "eg Min Str 8, Fatigues"
  armour name 03:
    label: "armour name 03"
    input: string
    placeholder: "eg Tactical Armor"
  armour axiom 03:
    label: "armour axiom 03"
    input: string
    placeholder: "eg Tech"
  armour adds 03:
    label: "armour adds 03"
    input: string
    placeholder: "eg +4"
  armour notes 03:
    label: "armour notes 03"
    input: string
    placeholder: "eg Min Str 8, Fatigues"
  armour name 04:
    label: "armour name 04"
    input: string
    placeholder: "eg Tactical Armor"
  armour axiom 04:
    label: "armour axiom 04"
    input: string
    placeholder: "eg Tech"
  armour adds 04:
    label: "armour adds 04"
    input: string
    placeholder: "eg +4"
  armour notes 04:
    label: "armour notes 04"
    input: string
    placeholder: "eg Min Str 8, Fatigues"
  armour name 05:
    label: "armour name 05"
    input: string
    placeholder: "eg Tactical Armor"
  armour axiom 05:
    label: "armour axiom 05"
    input: string
    placeholder: "eg Tech"
  armour adds 05:
    label: "armour adds 05"
    input: string
    placeholder: "eg +4"
  armour notes 05:
    label: "armour notes 05"
    input: string
    placeholder: "eg Min Str 8, Fatigues"
