fields:
  type:
    label: "Type"
    input: string
  size:
    label: "Size"
    input: string
    placeholder: "eg Small (10m long)"
  drive:
    label: "Drive"
    input: string
    placeholder: "eg Epstein, Thrusters, "
  sensors:
    label: "Sensors"
    input: integer
    placeholder: "eg -2, 0, 3, 6"
  hull:
    label: "Hull"
    input: string
    placeholder: "eg 1d6, 5d6"
  crew:
    label: "Crew"
    input: string
    placeholder: "eg 2 (4)"
  qualities:
    label: "Qualities"
    input: text
    rows: 20
    placeholder: "eg Hull plating, Hangar Bay, Luxury Amenities"
  weapons:
    label: "Weapons"
    input: text
    rows: 20
    placeholder: "eg Grapplers, Point Defense Cannons, Rail Guns, Torpedoes"
  flaws:
    label: "Flaws"
    input: text
    rows: 20
    placeholder: "eg Fragile, Lumbering, Wanted, Vulnerable Systems"
  crew role:
    label: "Crew Role"
    input: string
  role test:
    label: "Role Test"
    input: string
  notes:
    label: "Notes"
    input: text
    rows: 20
  image:
    label: "Image"
    input: integer
