fields:
  spell difficulty 01:
    label: "Spell Difficulty 01"
    input: string
  spell duration 01:
    label: "Spell Duration 01"
    input: string
  spell cost 01:
    label: "Spell Cost 01"
    input: string
  spell effect 01:
    label: "Spell Effect 01"
    input: text
    rows: 20
