fields:
  type:
    label: "type"
    input: string
    placeholder: "eg Shuttle, Strike Fighter"
  imageid:
    label: "imageid"
    input: integer
  hp:
    label: "hp"
    input: string
  ac:
    label: "ac"
    input: string
  armor:
    label: "armor"
    input: string
  speed:
    label: "speed"
    input: string
  power:
    label: "power"
    input: string
  mass:
    label: "mass"
    input: string
  crew min max:
    label: "crew min max"
    input: string
    placeholder: "eg 20/40"
  hull class:
    label: "hull class"
    input: string
    placeholder: "eg Fighter, Frigate"
  weapons:
    label: "weapons"
    input: text
    rows: 10
    placeholder: "eg Multifocal Laser (+3/1d4, AP 20)"
  defenses:
    label: "defenses"
    input: text
    rows: 10
    placeholder: "eg Hardened Polyceramic Overlay"
  fittings:
    label: "fittings"
    input: text
    rows: 10
    placeholder: "eg Extended Stores, Boarding Tubes"
  cost:
    label: "cost"
    input: string
    placeholder: "eg 5.973M base price, 298K maintenance"
  description:
    label: "description"
    input: text
    rows: 10
  crew:
    label: "crew"
    input: text
    rows: 10
    placeholder: "eg Bob the Gunner, Tom the Navigator"
  crew skill:
    label: "crew skill"
    input: string
  cargo:
    label: "cargo"
    input: text
    rows: 10
  npc cp:
    label: "npc cp"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 10