fields:
  occupation:
    label: "Occupation"
    input: string
    description: "Occupation"
  age:
    label: "Age"
    input: integer
    description: "Age"
  sex:
    label: "Sex"
    input: string
    description: "Sex"
  residence:
    label: "Residence"
    input: string
    description: "Residence"
  birthplace:
    label: "Birthplace"
    input: string
    description: "Birthplace"
  str:
    label: "Strength"
    input: integer
    description: ""
  con:
    label: "Constitution"
    input: integer
    description: ""
  siz:
    label: "Size"
    input: integer
    description: ""
  dex:
    label: "Dexterity"
    input: integer
    description: ""
  app:
    label: "Appearance"
    input: integer
    description: ""
  edu:
    label: "Education"
    input: integer
    description: ""
  int:
    label: "Intelligence"
    input: integer
    description: ""
  pow:
    label: "Power"
    input: integer
    description: ""
  skill name 1:
    label: "skill name 1"
    input: string
    description: "Accounting (5%)"
  skill value 1:
    label: "skill value 1"
    input: integer
    max: 99
  skill name 2:
    label: "skill name 2"
    input: string
    description: "Anthropology (1%)"
  skill value 2:
    label: "skill value 2"
    input: integer
    max: 99
  skill name 3:
    label: "skill name 3"
    input: string
    description: "Appraise (5%)"
  skill value 3:
    label: "skill value 3"
    input: integer
    max: 99
  skill name 4:
    label: "skill name 4"
    input: string
    description: "Archaeology (1%)"
  skill value 4:
    label: "skill value 4"
    input: integer
    max: 99
  skill name 5:
    label: "skill name 5"
    input: string
    description: "Art / Craft (5%)"
  skill value 5:
    label: "skill value 5"
    input: integer
    max: 99
  skill name 6:
    label: "skill name 6"
    input: string
    description: "Charm (15%)"
  skill value 6:
    label: "skill value 6"
    input: integer
    max: 99
  skill name 7:
    label: "skill name 7"
    input: string
    description: "Climb (20%)"
  skill value 7:
    label: "skill value 7"
    input: integer
    max: 99
  skill name 8:
    label: "skill name 8"
    input: string
    description: "Credit Rating (0%)"
  skill value 8:
    label: "skill value 8"
    input: integer
    max: 99
  skill name 9:
    label: "skill name 9"
    input: string
    description: "Cthulhu Mythos (0%)"
  skill value 9:
    label: "skill value 9"
    input: integer
    max: 99
  skill name 10:
    label: "skill name 10"
    input: string
    description: "Disguise (5%)"
  skill value 10:
    label: "skill value 10"
    input: integer
    max: 99
  skill name 11:
    label: "skill name 11"
    input: string
    description: "Dodge (half DEX)"
  skill value 11:
    label: "skill value 11"
    input: integer
    max: 99
  skill name 12:
    label: "skill name 12"
    input: string
    description: "Drive Auto (20%)"
  skill value 12:
    label: "skill value 12"
    input: integer
    max: 99
  skill name 13:
    label: "skill name 13"
    input: string
    description: "Elec.Repair (10%)"
  skill value 13:
    label: "skill value 13"
    input: integer
    max: 99
  skill name 14:
    label: "skill name 14"
    input: string
    description: "Fast Talk (5%)"
  skill value 14:
    label: "skill value 14"
    input: integer
    max: 99
  skill name 15:
    label: "skill name 15"
    input: string
    description: "Fighting (Brawl)(25%)"
  skill value 15:
    label: "skill value 15"
    input: integer
    max: 99
  skill name 16:
    label: "skill name 16"
    input: string
    description: "Firearms (Handgun)(20%)"
  skill value 16:
    label: "skill value 16"
    input: integer
    max: 99
  skill name 17:
    label: "skill name 17"
    input: string
    description: "Firearms (Rifle)"
  skill value 17:
    label: "skill value 17"
    input: integer
    max: 99
  skill name 18:
    label: "skill name 18"
    input: string
    description: "First Aid (30%)"
  skill value 18:
    label: "skill value 18"
    input: integer
    max: 99
  skill name 19:
    label: "skill name 19"
    input: string
    description: "History (5%)"
  skill value 19:
    label: "skill value 19"
    input: integer
    max: 99
  skill name 20:
    label: "skill name 20"
    input: string
    description: "Intimidate (15%)"
  skill value 20:
    label: "skill value 20"
    input: integer
    max: 99
  skill name 21:
    label: "skill name 21"
    input: string
    description: "Jump (20%)"
  skill value 21:
    label: "skill value 21"
    input: integer
    max: 99
  skill name 22:
    label: "skill name 22"
    input: string
    description: "Language (Other)(1%)"
  skill value 22:
    label: "skill value 22"
    input: integer
    max: 99
  skill name 23:
    label: "skill name 23"
    input: string
    description: "Language (Own)(EDU)"
  skill value 23:
    label: "skill value 23"
    input: integer
    max: 99
  skill name 24:
    label: "skill name 24"
    input: string
    description: "Law (5%)"
  skill value 24:
    label: "skill value 24"
    input: integer
    max: 99
  skill name 25:
    label: "skill name 25"
    input: string
    description: "Library Use (20%)"
  skill value 25:
    label: "skill value 25"
    input: integer
    max: 99
  skill name 26:
    label: "skill name 26"
    input: string
    description: "Listen (20%)"
  skill value 26:
    label: "skill value 26"
    input: integer
    max: 99
  skill name 27:
    label: "skill name 27"
    input: string
    description: "Locksmith (1%)"
  skill value 27:
    label: "skill value 27"
    input: integer
    max: 99
  skill name 28:
    label: "skill name 28"
    input: string
    description: "Mech. Repair (10%)"
  skill value 28:
    label: "skill value 28"
    input: integer
    max: 99
  skill name 29:
    label: "skill name 29"
    input: string
    description: "Medicine (1%)"
  skill value 29:
    label: "skill value 29"
    input: integer
    max: 99
  skill name 30:
    label: "skill name 30"
    input: string
    description: "Natural World (10%)"
  skill value 30:
    label: "skill value 30"
    input: integer
    max: 99
  skill name 31:
    label: "skill name 31"
    input: string
    description: "Navigate (10%)"
  skill value 31:
    label: "skill value 31"
    input: integer
    max: 99
  skill name 32:
    label: "skill name 32"
    input: string
    description: "Occult (5%)"
  skill value 32:
    label: "skill value 32"
    input: integer
    max: 99
  skill name 33:
    label: "skill name 33"
    input: string
    description: "Op.Hv.Machine (1%)"
  skill value 33:
    label: "skill value 33"
    input: integer
    max: 99
  skill name 34:
    label: "skill name 34"
    input: string
    description: "Persuade (10%)"
  skill value 34:
    label: "skill value 34"
    input: integer
    max: 99
  skill name 35:
    label: "skill name 35"
    input: string
    description: "Pilot (1%)"
  skill value 35:
    label: "skill value 35"
    input: integer
    max: 99
  skill name 36:
    label: "skill name 36"
    input: string
    description: "Psychology (10%)"
  skill value 36:
    label: "skill value 36"
    input: integer
    max: 99
  skill name 37:
    label: "skill name 37"
    input: string
    description: "Psychoanalysis (1%)"
  skill value 37:
    label: "skill value 37"
    input: integer
    max: 99
  skill name 38:
    label: "skill name 38"
    input: string
    description: "Ride (5%)"
  skill value 38:
    label: "skill value 38"
    input: integer
    max: 99
  skill name 39:
    label: "skill name 39"
    input: string
    description: "Science (1%)"
  skill value 39:
    label: "skill value 39"
    input: integer
    max: 99
  skill name 40:
    label: "skill name 40"
    input: string
    description: "Sleight of Hand (10%)"
  skill value 40:
    label: "skill value 40"
    input: integer
    max: 99
  skill name 41:
    label: "skill name 41"
    input: string
    description: "Spot Hidden (25%)"
  skill value 41:
    label: "skill value 41"
    input: integer
    max: 99
  skill name 42:
    label: "skill name 42"
    input: string
    description: "Stealth (20%)"
  skill value 42:
    label: "skill value 42"
    input: integer
    max: 99
  skill name 43:
    label: "skill name 43"
    input: string
    description: "Survival (10%)"
  skill value 43:
    label: "skill value 43"
    input: integer
    max: 99
  skill name 44:
    label: "skill name 44"
    input: string
    description: "Swim (20%)"
  skill value 44:
    label: "skill value 44"
    input: integer
    max: 99
  skill name 45:
    label: "skill name 45"
    input: string
    description: "Throw (20%)"
  skill value 45:
    label: "skill value 45"
    input: integer
    max: 99
  skill name 46:
    label: "skill name 46"
    input: string
    description: "Track (10%)"
  skill value 46:
    label: "skill value 46"
    input: integer
    max: 99
  skill name 47:
    label: "skill name 47"
    input: string
    description: ""
  skill value 47:
    label: "skill value 47"
    input: integer
    max: 99
  skill name 48:
    label: "skill name 48"
    input: string
    description: ""
  skill value 48:
    label: "skill value 48"
    input: integer
    max: 99
  skill name 49:
    label: "skill name 49"
    input: string
    description: ""
  skill value 49:
    label: "skill value 49"
    input: integer
    max: 99
  skill name 50:
    label: "skill name 50"
    input: string
    description: ""
  skill value 50:
    label: "skill value 50"
    input: integer
    max: 99
  skill name 51:
    label: "skill name 51"
    input: string
    description: ""
  skill value 51:
    label: "skill value 51"
    input: integer
    max: 99
  skill name 52:
    label: "skill name 52"
    input: string
    description: ""
  skill value 52:
    label: "skill value 52"
    input: integer
    max: 99
  skill name 53:
    label: "skill name 53"
    input: string
    description: ""
  skill value 53:
    label: "skill value 53"
    input: integer
    max: 99
  skill name 54:
    label: "skill name 54"
    input: string
    description: ""
  skill value 54:
    label: "skill value 54"
    input: integer
    max: 99
  skill name 55:
    label: "skill name 55"
    input: string
    description: ""
  skill value 55:
    label: "skill value 55"
    input: integer
    max: 99
  skill name 56:
    label: "skill name 56"
    input: string
    description: ""
  skill value 56:
    label: "skill value 56"
    input: integer
    max: 99
  skill name 57:
    label: "skill name 57"
    input: string
    description: ""
  skill value 57:
    label: "skill value 57"
    input: integer
    max: 99
  skill name 58:
    label: "skill name 58"
    input: string
    description: ""
  skill value 58:
    label: "skill value 58"
    input: integer
    max: 99
  skill name 59:
    label: "skill name 59"
    input: string
    description: ""
  skill value 59:
    label: "skill value 59"
    input: integer
    max: 99
  skill name 60:
    label: "skill name 60"
    input: string
    description: ""
  skill value 60:
    label: "skill value 60"
    input: integer
    max: 99
  skill name 61:
    label: "skill name 61"
    input: string
    description: ""
  skill value 61:
    label: "skill value 61"
    input: integer
    max: 99
  skill name 62:
    label: "skill name 62"
    input: string
    description: ""
  skill value 62:
    label: "skill value 62"
    input: integer
    max: 99
  skill name 63:
    label: "skill name 63"
    input: string
    description: ""
  skill value 63:
    label: "skill value 63"
    input: integer
    max: 99
  skill name 64:
    label: "skill name 64"
    input: string
    description: ""
  skill value 64:
    label: "skill value 64"
    input: integer
    max: 99
  skill name 65:
    label: "skill name 65"
    input: string
    description: ""
  skill value 65:
    label: "skill value 65"
    input: integer
    max: 99
  skill name 66:
    label: "skill name 66"
    input: string
    description: ""
  skill value 66:
    label: "skill value 66"
    input: integer
    max: 99
  weapon_name_01:
    label: "Weapon Name 01"
    input: string
  weapon_reg_01:
    label: "Weapon Reg 01"
    input: integer
  weapon_hard_01:
    label: "Weapon Hard 01"
    input: integer
  weapon_ext_01:
    label: "Weapon Ext 01"
    input: integer
  weapon_damage_01:
    label: "Weapon Damage 01"
    input: string
  weapon_range_01:
    label: "Weapon Range 01"
    input: string
  weapon_attacks_01:
    label: "Weapon Attacks 01"
    input: integer
  weapon_ammo_01:
    label: "Weapon Ammo 01"
    input: integer
  weapon_malf_01:
    label: "Weapon Malf 01"
    input: string
  weapon_name_02:
    label: "Weapon Name 02"
    input: string
  weapon_reg_02:
    label: "Weapon Reg 02"
    input: integer
  weapon_hard_02:
    label: "Weapon Hard 02"
    input: integer
  weapon_ext_02:
    label: "Weapon Ext 02"
    input: integer
  weapon_damage_02:
    label: "Weapon Damage 02"
    input: string
  weapon_range_02:
    label: "Weapon Range 02"
    input: string
  weapon_attacks_02:
    label: "Weapon Attacks 02"
    input: integer
  weapon_ammo_02:
    label: "Weapon Ammo 02"
    input: integer
  weapon_malf_02:
    label: "Weapon Malf 02"
    input: string
  weapon_name_03:
    label: "Weapon Name 03"
    input: string
  weapon_reg_03:
    label: "Weapon Reg 03"
    input: integer
  weapon_hard_03:
    label: "Weapon Hard 03"
    input: integer
  weapon_ext_03:
    label: "Weapon Ext 03"
    input: integer
  weapon_damage_03:
    label: "Weapon Damage 03"
    input: string
  weapon_range_03:
    label: "Weapon Range 03"
    input: string
  weapon_attacks_03:
    label: "Weapon Attacks 03"
    input: integer
  weapon_ammo_03:
    label: "Weapon Ammo 03"
    input: integer
  weapon_malf_03:
    label: "Weapon Malf 03"
    input: string
  weapon_name_04:
    label: "Weapon Name 04"
    input: string
  weapon_reg_04:
    label: "Weapon Reg 04"
    input: integer
  weapon_hard_04:
    label: "Weapon Hard 04"
    input: integer
  weapon_ext_04:
    label: "Weapon Ext 04"
    input: integer
  weapon_damage_04:
    label: "Weapon Damage 04"
    input: string
  weapon_range_04:
    label: "Weapon Range 04"
    input: string
  weapon_attacks_04:
    label: "Weapon Attacks 04"
    input: integer
  weapon_ammo_04:
    label: "Weapon Ammo 04"
    input: integer
  weapon_malf_04:
    label: "Weapon Malf 04"
    input: string
  weapon_name_05:
    label: "Weapon Name 05"
    input: string
  weapon_reg_05:
    label: "Weapon Reg 05"
    input: integer
  weapon_hard_05:
    label: "Weapon Hard 05"
    input: integer
  weapon_ext_05:
    label: "Weapon Ext 05"
    input: integer
  weapon_damage_05:
    label: "Weapon Damage 05"
    input: string
  weapon_range_05:
    label: "Weapon Range 05"
    input: string
  weapon_attacks_05:
    label: "Weapon Attacks 05"
    input: integer
  weapon_ammo_05:
    label: "Weapon Ammo 05"
    input: integer
  weapon_malf_05:
    label: "Weapon Malf 05"
    input: string
  weapon_name_06:
    label: "Weapon Name 06"
    input: string
  weapon_reg_06:
    label: "Weapon Reg 06"
    input: integer
  weapon_hard_06:
    label: "Weapon Hard 06"
    input: integer
  weapon_ext_06:
    label: "Weapon Ext 06"
    input: integer
  weapon_damage_06:
    label: "Weapon Damage 06"
    input: string
  weapon_range_06:
    label: "Weapon Range 06"
    input: string
  weapon_attacks_06:
    label: "Weapon Attacks 06"
    input: integer
  weapon_ammo_06:
    label: "Weapon Ammo 06"
    input: integer
  weapon_malf_06:
    label: "Weapon Malf 06"
    input: string
  hit points curr:
    label: "Hit Points Current"
    input: integer
  hit points max:
    label: "Hit Points Max"
    input: integer
  magic points curr:
    label: "Magic Points Current"
    input: integer
  magic points max:
    label: "Magic Points Max"
    input: integer
  sanity curr:
    label: "Sanity Current"
    input: integer
  sanity max:
    label: "Sanity Max"
    input: integer
  luck curr:
    label: "Luck Current"
    input: integer
  luck max:
    label: "Luck Max"
    input: integer
  major wound:
    label: "Major Wound"
    input: checkbox
  temp insane:
    label: "Temp Insane"
    input: checkbox
  indef insane:
    label: "Indef Insane"
    input: checkbox
  notes: 
    label: "Notes"
    description: "Notes"
    input: text
    rows: 10
  personal: 
    label: "Personal"
    input: text
    rows: 20
  Beliefs: 
    label: "beliefs"
    input: text
    rows: 20
  people: 
    label: "People"
    input: text
    rows: 20
  locations: 
    label: "Locations"
    input: text
    rows: 20
  treasures: 
    label: "Treasures"
    input: text
    rows: 20
  traits: 
    label: "Traits"
    input: text
    rows: 20
  injuries: 
    label: "Injuries"
    input: text
    rows: 20
  phobias: 
    label: "Phobias"
    input: text
    rows: 20
  tomes: 
    label: "Tomes"
    input: text
    rows: 20
  encounters: 
    label: "Encounters"
    input: text
    rows: 20
  gear: 
    label: "Gear"
    input: text
    rows: 20
  assets: 
    label: "Assets"
    input: text
    rows: 20
  spending level:
    label: "Spending Level"
    input: string
  money:
    label: "Money"
    input: integer
