fields:
  ruler:
    label: "Ruler"
    input: string
    placeholder: "Ludwig 14th"
  legitimacy:
    label: "Legitimacy"
    input: string
  faction name 01:
    label: "faction name 01"
    input: string
  faction power 01:
    label: "faction power 01"
    input: integer
    min: 0
  faction tn 01:
    label: "faction tn 01"
    input: integer
  faction focus 01:
    label: "faction focus 01"
    input: integer
  faction notes 01:
    label: "faction notes 01"
    input: text
    rows: 10
  faction name 02:
    label: "faction name 02"
    input: string
  faction power 02:
    label: "faction power 02"
    input: integer
    min: 0
  faction tn 02:
    label: "faction tn 02"
    input: integer
  faction focus 02:
    label: "faction focus 02"
    input: integer
  faction notes 02:
    label: "faction notes 02"
    input: text
    rows: 10
  faction name 03:
    label: "faction name 03"
    input: string
  faction power 03:
    label: "faction power 03"
    input: integer
    min: 0
  faction tn 03:
    label: "faction tn 03"
    input: integer
  faction focus 03:
    label: "faction focus 03"
    input: integer
  faction notes 03:
    label: "faction notes 03"
    input: text
    rows: 10
  faction name 04:
    label: "faction name 04"
    input: string
  faction power 04:
    label: "faction power 04"
    input: integer
    min: 0
  faction tn 04:
    label: "faction tn 04"
    input: integer
  faction focus 04:
    label: "faction focus 04"
    input: integer
  faction notes 04:
    label: "faction notes 04"
    input: text
    rows: 10
  faction name 05:
    label: "faction name 05"
    input: string
  faction power 05:
    label: "faction power 05"
    input: integer
    min: 0
  faction tn 05:
    label: "faction tn 05"
    input: integer
  faction focus 05:
    label: "faction focus 05"
    input: integer
  faction notes 05:
    label: "faction notes 05"
    input: text
    rows: 10
  faction name 06:
    label: "faction name 06"
    input: string
  faction power 06:
    label: "faction power 06"
    input: integer
    min: 0
  faction tn 06:
    label: "faction tn 06"
    input: integer
  faction focus 06:
    label: "faction focus 06"
    input: integer
  faction notes 06:
    label: "faction notes 06"
    input: text
    rows: 10
  faction name 07:
    label: "faction name 07"
    input: string
  faction power 07:
    label: "faction power 07"
    input: integer
    min: 0
  faction tn 07:
    label: "faction tn 07"
    input: integer
  faction focus 07:
    label: "faction focus 07"
    input: integer
  faction notes 07:
    label: "faction notes 07"
    input: text
    rows: 10
  faction name 08:
    label: "faction name 08"
    input: string
  faction power 08:
    label: "faction power 08"
    input: integer
    min: 0
  faction tn 08:
    label: "faction tn 08"
    input: integer
  faction focus 08:
    label: "faction focus 08"
    input: integer
  faction notes 08:
    label: "faction notes 08"
    input: text
    rows: 10
  faction name 09:
    label: "faction name 09"
    input: string
  faction power 09:
    label: "faction power 09"
    input: integer
    min: 0
  faction tn 09:
    label: "faction tn 09"
    input: integer
  faction focus 09:
    label: "faction focus 09"
    input: integer
  faction notes 09:
    label: "faction notes 09"
    input: text
    rows: 10
  faction name 10:
    label: "faction name 10"
    input: string
  faction power 10:
    label: "faction power 10"
    input: integer
    min: 0
  faction tn 10:
    label: "faction tn 10"
    input: integer
  faction focus 10:
    label: "faction focus 10"
    input: integer
  faction notes 10:
    label: "faction notes 10"
    input: text
    rows: 10
