fields:
# name
  level:
    label: "level"
    placeholder: "eg 1, 2, 20"
    input: string
  rarity:
    label: "rarity"
    placeholder: "eg uncommon, rare"
    input: string
  alignment:
    label: "alignment"
    placeholder: "eh CN, LE, CG, NG"
    input: string
  size:
    label: "size"
    placeholder: "eg tiny, normal, large"
    input: string
  traits:
    label: "traits"
    placeholder: "eg beast, amphibious, monitor, aeon, abberation, celestial"
    input: string
  about:
    label: "about"
    input: text
    rows: 10
  type:
    label: "type"
    input: text
    placeholder: "eg creature, fighter, wizard"
  perception:
    label: "perception"
    description: "eg +12, darkvision"
    input: string
  languages:
    label: "languages"
    input: string
  skills:
    label: "skills"
    input: string
  str mod:
    label: "str mod"
    input: string
  dex mod:
    label: "dex mod"
    input: string
  con mod:
    label: "con mod"
    input: string
  int mod:
    label: "int mod"
    input: string
  wis mod:
    label: "wis mod"
    input: string
  cha mod:
    label: "cha mod"
    input: string
  ac:
    label: "ac"
    placeholder: "eg 17"
    input: string
  st fort:
    label: "st fort"
    input: string
  st ref:
    label: "st ref"
    input: string
  st will:
    label: "st will"
    input: string
  st notes:
    label: "st notes"
    placeholder: "eg +1 to all saves vs. magic"
    input: string
  hp:
    label: "hp"
    input: string
  immunities:
    label: "immunities"
    input: string
  weaknesses:
    label: "weaknesses"
    input: string
  resistances:
    label: "resistances"
    input: string
  abilities:
    label: "abilities"
    input: text
    rows: 10
  speed:
    label: "speed"
    placeholder: "eg 30 ft, fly 60 ft"
    input: string
  melee:
    label: "melee"
    placeholder: "eg holy mace +28 (good, magical, shove), 2d6+15 bludgeoning"
    input: text
    rows: 10
  ranged:
    label: "ranged"
    input: text
    rows: 10
  spells:
    label: "spells"
    input: text
    rows: 10
  rituals:
    label: "rituals"
    input: text
    rows: 10
  description:
    label: "description"
    input: text
    rows: 20
  items:
    label: "items"
    input: text
    rows: 10
