fields:
#
# Character basics
#
  character_name:
    input: string
    label: "Character Name"
    description: "The name of your character"
    placeholder: "Hildr Brïnfrior"
    required: true
  player_name:
    input: string
    label: "Player Name"
    description: "The name of the player"
    placeholder: "Gorkam Worka"
#
# Character class and level
#
  class: 
    input: string 
    label: "Class"
    description: "Class of your character"
    placeholder: "Priest"
  level:
    input: integer
    label: "Level"
    description: "Your character level"
    placeholder: "13"
  hero_points:
    input: integer
    label: "Hero Points"
    description: "Your character hero points"
    placeholder: "10"
  experience:
    input: integer
    label: "Experience Points"
    description: "Number of experience points"
    placeholder: "1250"
#
# Character Role Playing and history
#
  ancestry_and_heritages:
    input: text
    rows: 3
    label: "Ancestry & Heritages"
    description: "Ancestry and heritages of your character"
    placeholder: "Daughter of the Frozen Lords of Brïn"
  background:
    input: text
    rows: 5
    label: "Background"
    description: "Background infos for your character"
  size:
    input: string 
    label: "Size"
    description: "Character size, including units (eg 1.85m or 6ft)"
    placeholder: "1.85m"
  alignement:
    input: string
    label: "Alignment"
    description: "Character alignment, eg Chaotic Neutral"
    placeholder: "Chaotic Good"
  traits:
    input: string
    label: "Traits"
    description: "Character Traits"
    placeholder: ""  
  deity:
    input: string
    label: "Deity"
    description: "Worshipped deity"
    placeholder: "The Cold Flame"
#
# Character Attributs 
#
  strength_score:
    input: integer
    label: "Strength"
    description: "Strength of your character"
    placeholder: "10"
    min: 1
  dexterity_score:
    input: integer
    label: "Dexterity"
    description: "Dexterity of your character"
    placeholder: "10"
    min: 1
  constitution_score:
    input: integer
    label: "Constitution"
    description: "Constitution of your character"
    placeholder: "10"
    min: 1
  intelligence_score:
    input: integer
    label: "Intelligence"
    description: "Intelligence of your character"
    placeholder: "10"
    min: 1
  wisdom_score:
    input: integer
    label: "Wisdom"
    description: "Wisdom of your character"
    placeholder: "10"
    min: 1
  charisma_score:
    input: integer
    label: "Charisma"
    description: "Charisma of your character"
    placeholder: "10"
    min: 1
#
# Class DC
#
  class_dc_ability:
    input: select
    label: "Class Main Ability"
    options:
      Strength: STR
      Dexterity: DEX
      Constitution: CON
      Intelligence: INT
      Wisdom: WIS
      Charism: CHA
  class_dc_proficiency:
    input: select
    label: "Class DC Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  class_dc_item:
    input: integer
    label: "Class DC Item Bonus"
    placeholder: 0
#
# Armor Class
#
  ac_cap:
    input: integer
    label: "Armor Class Cap"
  ac_proficiency:
    input: select
    label: "Armor Class Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  ac_item:
    input: integer
    label: "Armor Class Item Bonus"
    placeholder: 0
  ua_proficiency:
    input: select
    label: "Unarmored Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  la_proficiency:
    input: select
    label: "Light Armor Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  ma_proficiency:
    input: select
    label: "Medium Armor Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  ha_proficiency:
    input: select
    label: "Heavy Armor Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  shield_ac_bonus:
    input: integer
    label: "Shield Armor Class Bonus"
  shield_hardness:
    input: integer
    label: "Shield Hardness"
  shield_max_hp:
    input: integer
    label: "Shield Max HP"
  shield_break_threshold:
    input: integer
    label: "Shield Break Threshold"
  shield_current_hp:
    input: integer
    label: "Shield Current HP"
#
# Speed and Movement
#
  speed:
    input: string
    label: "Speed"
    description: "Speed including units, eg 9m, 18ft"
  movement:
    input: string
    label: "Movement"
    description: "Movement types and notes including units, eg 9m (fly) 17m (swimming)"
#
# Saving throws
#
  fortitude_save_proficiency:
    input: select
    label: "Fortitude Save Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  fortitude_save_item:
    input: integer
    label: "Fortitude Save Item Bonus"
    placeholder: 0
  reflex_save_proficiency:
    input: select
    label: "Reflex Save Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  reflex_save_item:
    input: integer
    label: "Reflex Save Item Bonus"
    placeholder: 0
  will_save_proficiency:
    input: select
    label: "Will Save Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  will_save_item:
    input: integer
    label: "Will Save Item Bonus"
    placeholder: 0
  saving_throws_notes:
    input: text
    label: "Saving Throws Notes"
    rows: 3
#
# Hit Points
#
  hp_max:
    input: integer
    label: "Max HP"
    description: "Character max hit points"
  hp_current:
    input: integer
    label: "Current HP"
    description: "Character current hit points"
  hp_temp:
    input: integer
    label: "Temporary HP"
    description: "Character temporary hit points"
  hp_resists:
    input: text
    label: "Resistances And Immunities"
    rows: 3
  hp_conditions:
    input: text
    label: "Conditions"
    rows: 3
#
# Perception Block
#
  perception_proficiency:
    input: select
    label: "Perception Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  perception_item:
    input: integer
    label: "Preception Item Bonus" 
  perception_senses:
    input: text
    label: "Senses"
    rows: 3
#
# Skills
#
  acrobatics_proficiency:
    input: select
    label: "Acrobatics Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  acrobatics_item_modifier:
    input: integer
    label: "Acrobatics Item Modifier"
    placeholder: 0
  ########
  arcana_proficiency:
    input: select
    label: "Arcana Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  arcana_item_modifier:
    input: integer
    label: "Arcana Item Modifier"
    placeholder: 0
  ###############
  athletics_proficiency:
    input: select
    label: "Athletics Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  athletics_item_modifier:
    input: integer
    label: "Athletics Item Modifier"
    placeholder: 0
  ###############
  crafting_proficiency:
    input: select
    label: "Crafting Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  crafting_item_modifier:
    input: integer
    label: "Crafting Item Modifier"
    placeholder: 0
  ###############
  deception_proficiency:
    input: select
    label: "Deception Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  deception_item_modifier:
    input: integer
    label: "Deception Item Modifier"
    placeholder: 0
  ###############
  diplomacy_proficiency:
    input: select
    label: "Diplomacy Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  diplomacy_item_modifier:
    input: integer
    label: "Diplomacy Item Modifier"
    placeholder: 0
  ###############
  intimidation_proficiency:
    input: select
    label: "Intimidation Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  intimidation_item_modifier:
    input: integer
    label: "Intimidation Item Modifier"
    placeholder: 0
  ###############
  #lores:
  lores_csv:
    input: string
    label: "Lores"
    description: "Formatted string for lores skills. ¤ Format: LoreName | Ability | Proficiency | Item Mod; LoreName2 | DEX | TRAINED | 4 ; ¤ Possible value for  Ability { STR, DEX, CON, INT, WIS, CHA } default: INT ¤ Possible value for Proficiency { UNTRAINED, TRAINED, EXPERT, MASTER, LEGENDARY } default: UNTRAINED"
    placeholder: " Common | INT | TRAINED | 2 ; Chaos | CHA | MASTER ;"
  #####################
  medicine_proficiency:
    input: select
    label: "Medicine Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  medicine_item_modifier:
    input: integer
    label: "Item Modifier"
    placeholder: 0
  ###############
  nature_proficiency:
    input: select
    label: "Nature Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  nature_item_modifier:
    input: integer
    label: "Nature Item Modifier"
    placeholder: 0
  ###############
  occultism_proficiency:
    input: select
    label: "Occultism Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  occultism_item_modifier:
    input: integer
    label: "Occultism Item Modifier"
    placeholder: 0
  ###############
  performance_proficiency:
    input: select
    label: "Performance Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  performance_item_modifier:
    input: integer
    label: "Performance Item Modifier"
    placeholder: 0
  ###############
  religion_proficiency:
    input: select
    label: "Religion Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  religion_item_modifier:
    input: integer
    label: "Religion Item Modifier"
    placeholder: 0
  ###############
  society_proficiency:
    input: select
    label: "Society Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  society_item_modifier:
    input: integer
    label: "Society Item Modifier"
    placeholder: 0
  ###############
  stealth_proficiency:
    input: select
    label: "Stealth Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  stealth_item_modifier:
    input: integer
    label: "Stealth Item Modifier"
    placeholder: 0
  ###############
  survival_proficiency:
    input: select
    label: "Survival Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  survival_item_modifier:
    input: integer
    label: "Survival Item Modifier"
    placeholder: 0
  ###############
  thievery_proficiency:
    input: select
    label: "Thievery Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  thievery_item_modifier:
    input: integer
    label: "Thievery Item Modifier"
    placeholder: 0
#
# Weapon Proficiency Block
#
  simple_weapon_proficiency:
    input: select
    label: "Simple Weapon Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  martial_weapon_proficiency:
    input: select
    label: "Martial Weapon Proficiency"
    options:
     Untrained : 0
     Trained : 2
     Expert : 4
     Master: 6
     Legendary: 8
  other_weapon_proficiency_csv:
    input: string
    label: "Other Weapons Proficiency"
    description: "Formatted string for other weapons proficiency. ¤ Format: WeaponName | Proficiency ; WeaponName2 | TRAINED ; ¤ Possible value for Proficiency { UNTRAINED, TRAINED, EXPERT, MASTER, LEGENDARY } default: UNTRAINED"
    placeholder: " Whip | TRAINED ; Urgosh | MASTER ;"
#
# Language
#
  Language:
    input: string
    label: "Language"
    description: "Language Spoken by the character"
#
# Feats Collections
#
  col_ancestry_feats:
    input: string
    label: "Ancestry Feats and Ability"
    description: "List of ancestry Feats and Abilities your character possesses. Block ID list divided by | "
    placeholder: " 685 | 857 | 980 "
  col_skill_feats:
    input: string
    label: "Skill Feats"
    description: "List of Skill Feats your character possesses. Block ID list divided by | "
    placeholder: " 65 | 57 | 9810 "
  col_class_feats:
    input: string
    label: "Class Feats and Abilities"
    description: "List of Class Feats and Abilities your character possesses. Block ID list divided by | "
    placeholder: " 2585 | 5731 | 9410 "
  col_general_feats:
    input: string
    label: "General Feats"
    description: "List of Skill Feats your character possesses. Block ID list divided by | "
    placeholder: " 4645 | 547 | 9814 "
  str_score:
    input: integer
    label: "str score"
  dex_score:
    input: integer
    label: "dex score"
  con_score:
    input: integer
    label: "con score"
  int_score:
    input: integer
    label: "int score"
  wis_score:
    input: integer
    label: "wis score"
  cha_score:
    input: integer
    label: "cha score"
  str_mod:
    input: integer
    label: "str mod"
  dex_mod:
    input: integer
    label: "dex mod"
  con_mod:
    input: integer
    label: "con mod"
  int_mod:
    input: integer
    label: "int mod"
  wis_mod:
    input: integer
    label: "wis mod"
  cha_mod:
    input: integer
    label: "cha mod"
### magic
### spell slots
  spell slots max 01:
    label: "Spell slots max 01"
    description: "Maximum slots for spell level 01"
    input: integer
  spell slots curr 01:
    label: "Spell slots curr 01"
    description: "Available slots for spell level 01"
    input: integer
  spell slots max 02:
    label: "Spell slots max 02"
    description: "Maximum slots for spell level 02"
    input: integer
  spell slots curr 02:
    label: "Spell slots curr 02"
    description: "Available slots for spell level 02"
    input: integer
  spell slots max 03:
    label: "Spell slots max 03"
    description: "Maximum slots for spell level 03"
    input: integer
  spell slots curr 03:
    label: "Spell slots curr 03"
    description: "Available slots for spell level 03"
    input: integer
  spell slots max 04:
    label: "Spell slots max 04"
    description: "Maximum slots for spell level 04"
    input: integer
  spell slots curr 04:
    label: "Spell slots curr 04"
    description: "Available slots for spell level 04"
    input: integer
  spell slots max 05:
    label: "Spell slots max 05"
    description: "Maximum slots for spell level 05"
    input: integer
  spell slots curr 05:
    label: "Spell slots curr 05"
    description: "Available slots for spell level 05"
    input: integer
  spell slots max 06:
    label: "Spell slots max 06"
    description: "Maximum slots for spell level 06"
    input: integer
  spell slots curr 06:
    label: "Spell slots curr 06"
    description: "Available slots for spell level 06"
    input: integer
  spell slots max 07:
    label: "Spell slots max 07"
    description: "Maximum slots for spell level 07"
    input: integer
  spell slots curr 07:
    label: "Spell slots curr 07"
    description: "Available slots for spell level 07"
    input: integer
  spell slots max 08:
    label: "Spell slots max 08"
    description: "Maximum slots for spell level 08"
    input: integer
  spell slots curr 08:
    label: "Spell slots curr 08"
    description: "Available slots for spell level 08"
    input: integer
  spell slots max 09:
    label: "Spell slots max 09"
    description: "Maximum slots for spell level 09"
    input: integer
  spell slots curr 09:
    label: "Spell slots curr 09"
    description: "Available slots for spell level 09"
    input: integer
  spell slots max 10:
    label: "Spell slots max 10"
    description: "Maximum slots for spell level 10"
    input: integer
  spell slots curr 10:
    label: "Spell slots curr 10"
    description: "Available slots for spell level 10"
    input: integer
### cantrips
  cantrip level:
    label: "Cantrip Level"
    input: integer
### focus spells
  focus points curr:
    label: "Focus points curr"
    description: "Current Focus Points"
    input: integer
  focus points max:
    label: "Focus points max"
    description: "Maximum Focus Points"
    input: integer
