#
# IMPORTANT: this schema is incomplete and only contains the changes.
# This needs a full export from WA
#
fields:
  class 1:
    label: "class 1"
    input: string
    description: "Name of the class."
    placeholder: "eg Ranger, Warrior"
  level 1:
    label: "level 1"
    input: string
    description: "Level of this class."
  class 2:
    label: "class 2"
    input: string
    description: "Name of the class."
    placeholder: "eg Ranger, Warrior"
  level 2:
    label: "level 2"
    input: string
    description: "Level of this class."
  class 3:
    label: "class 3"
    input: string
    description: "Name of the class."
    placeholder: "eg Ranger, Warrior"
  level 3:
    label: "level 3"
    input: string
    description: "Level of this class."
  class 4:
    label: "class 4"
    input: string
    description: "Name of the class."
    placeholder: "eg Ranger, Warrior"
  level 4:
    label: "level 4"
    input: string
    description: "Level of this class."
  acrobatics prof:
    label: "acrobatics prof"
    input: checkbox
  animal handling prof:
    label: "animal handling prof"
    input: checkbox
  arcana prof:
    label: "arcana prof"
    input: checkbox
  athletics prof:
    label: "athletics prof"
    input: checkbox
  deception prof:
    label: "deception prof"
    input: checkbox
  history prof:
    label: "history prof"
    input: checkbox
  insight prof:
    label: "insight prof"
    input: checkbox
  intimidation prof:
    label: "intimidation prof"
    input: checkbox
  investigation prof:
    label: "investigation prof"
    input: checkbox
  medicine prof:
    label: "medicine prof"
    input: checkbox
  nature prof:
    label: "nature prof"
    input: checkbox
  perception prof:
    label: "perception prof"
    input: checkbox
  performance prof:
    label: "performance prof"
    input: checkbox
  persuasion prof:
    label: "persuasion prof"
    input: checkbox
  religion prof:
    label: "religion prof"
    input: checkbox
  sleight of hand prof:
    label: "sleight of hand prof"
    input: checkbox
  stealth prof:
    label: "stealth prof"
    input: checkbox
  survival prof:
    label: "survival prof"
    input: checkbox
  acrobatics exp:
    label: "acrobatics exp"
    input: checkbox
  animal handling exp:
    label: "animal handling exp"
    input: checkbox
  arcana exp:
    label: "arcana exp"
    input: checkbox
  athletics exp:
    label: "athletics exp"
    input: checkbox
  deception exp:
    label: "deception exp"
    input: checkbox
  history exp:
    label: "history exp"
    input: checkbox
  insight exp:
    label: "insight exp"
    input: checkbox
  intimidation exp:
    label: "intimidation exp"
    input: checkbox
  investigation exp:
    label: "investigation exp"
    input: checkbox
  medicine exp:
    label: "medicine exp"
    input: checkbox
  nature exp:
    label: "nature exp"
    input: checkbox
  perception exp:
    label: "perception exp"
    input: checkbox
  performance exp:
    label: "performance exp"
    input: checkbox
  persuasion exp:
    label: "persuasion exp"
    input: checkbox
  religion exp:
    label: "religion exp"
    input: checkbox
  sleight of hand exp:
    label: "sleight of hand exp"
    input: checkbox
  stealth exp:
    label: "stealth exp"
    input: checkbox
  survival exp:
    label: "survival exp"
    input: checkbox
  notes:
    label: "notes"
    input: text
    rows: 10
  jack of all trades:
    label: "jack of all trades"
    input: checkbox
  strength save prof:
    label: "strength save prof"
    input: checkbox
  dexterity save prof:
    label: "dexterity save prof"
    input: checkbox
  constitution save prof:
    label: "constitution save prof"
    input: checkbox
  intelligence save prof:
    label: "intelligence save prof"
    input: checkbox
  wisdom save prof:
    label: "wisdom save prof"
    input: checkbox
  charisma save prof:
    label: "charisma save prof"
    input: checkbox
  strength save exp:
    label: "strength save exp"
    input: checkbox
  dexterity save exp:
    label: "dexterity save exp"
    input: checkbox
  constitution save exp:
    label: "constitution save exp"
    input: checkbox
  intelligence save exp:
    label: "intelligence save exp"
    input: checkbox
  wisdom save exp:
    label: "wisdom save exp"
    input: checkbox
  charisma save exp:
    label: "charisma save exp"
    input: checkbox
  spellcasting ability:
    label: "spellcasting ability"
    input: select
    options:
      NONE: NONE
      INT: INT
      WIS: WIS
      CHA: CHA
  attack 01:
    label: "attack 01"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 01:
    label: "attack prof 01"
    input: checkbox
  attack dmg 01:
    label: "attack dmg 01"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 01:
    label: "attack dmg type 01"
    input: string
    placeholder: "eg piercing"
  attack props 01:
    label: "attack props 01"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 02:
    label: "attack 02"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 02:
    label: "attack prof 02"
    input: checkbox
  attack dmg 02:
    label: "attack dmg 02"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 02:
    label: "attack dmg type 02"
    input: string
    placeholder: "eg piercing"
  attack props 02:
    label: "attack props 02"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 03:
    label: "attack 03"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 03:
    label: "attack prof 03"
    input: checkbox
  attack dmg 03:
    label: "attack dmg 03"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 03:
    label: "attack dmg type 03"
    input: string
    placeholder: "eg piercing"
  attack props 03:
    label: "attack props 03"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 04:
    label: "attack 04"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 04:
    label: "attack prof 04"
    input: checkbox
  attack dmg 04:
    label: "attack dmg 04"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 04:
    label: "attack dmg type 04"
    input: string
    placeholder: "eg piercing"
  attack props 04:
    label: "attack props 04"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 05:
    label: "attack 05"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 05:
    label: "attack prof 05"
    input: checkbox
  attack dmg 05:
    label: "attack dmg 05"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 05:
    label: "attack dmg type 05"
    input: string
    placeholder: "eg piercing"
  attack props 05:
    label: "attack props 05"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 06:
    label: "attack 06"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 06:
    label: "attack prof 06"
    input: checkbox
  attack dmg 06:
    label: "attack dmg 06"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 06:
    label: "attack dmg type 06"
    input: string
    placeholder: "eg piercing"
  attack props 06:
    label: "attack props 06"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 07:
    label: "attack 07"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 07:
    label: "attack prof 07"
    input: checkbox
  attack dmg 07:
    label: "attack dmg 07"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 07:
    label: "attack dmg type 07"
    input: string
    placeholder: "eg piercing"
  attack props 07:
    label: "attack props 07"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 08:
    label: "attack 08"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 08:
    label: "attack prof 08"
    input: checkbox
  attack dmg 08:
    label: "attack dmg 08"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 08:
    label: "attack dmg type 08"
    input: string
    placeholder: "eg piercing"
  attack props 08:
    label: "attack props 08"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 09:
    label: "attack 09"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 09:
    label: "attack prof 09"
    input: checkbox
  attack dmg 09:
    label: "attack dmg 09"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 09:
    label: "attack dmg type 09"
    input: string
    placeholder: "eg piercing"
  attack props 09:
    label: "attack props 09"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack 10:
    label: "attack 10"
    input: string
    placeholder: "eg Crossbow, Dagger"
  attack prof 10:
    label: "attack prof 10"
    input: checkbox
  attack dmg 10:
    label: "attack dmg 10"
    input: string
    placeholder: "eg 2d6"
  attack dmg type 10:
    label: "attack dmg type 10"
    input: string
    placeholder: "eg piercing"
  attack props 10:
    label: "attack props 10"
    input: string
    placeholder: "eg Finesse, light, thrown (range 20/60)"
  attack attr 01:
    label: "attack attr 01"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 02:
    label: "attack attr 02"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 03:
    label: "attack attr 03"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 04:
    label: "attack attr 04"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 05:
    label: "attack attr 05"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 06:
    label: "attack attr 06"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 07:
    label: "attack attr 07"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 08:
    label: "attack attr 08"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 09:
    label: "attack attr 09"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA
  attack attr 10:
    label: "attack attr 10"
    input: select
    options:
      STR: STR
      DEX: DEX
      CON: CON
      INT: INT
      WIS: WIS
      CHA: CHA



