fields:
  type:
    label: "ship type"
    input: string
    description: "Type of the ship"
    placeholder: "eg Bireme, Canoe, Longboat, Galley"
  range:
    label: "range"
    input: string
    description: "How long the ship may remain at sea without resupplying (in days)"
    placeholder: "eg 5 days"
  maneuver:
    label: "maneuver"
    input: integer
    description: "Maneuver rating of the ship"
    placeholder: "eg 1 (value between 0 and 3, number of additional d20 for sailing tests)"
  impact damage:
    label: "impact damage"
    input: integer
    description: "How much damage the ship does when ramming (in d6)"
    placeholder: "eg 4 (for 4d6)"
  qualities:
    label: "qualities"
    input: string
    description: "Qualities of the ship"
    placeholder: "eg Agile, Deep draft, Galley, Light craft, Ponderous, Portage, Ram, Rugged, Shallow draft, Ship"
  captain:
    label: "captain"
    input: string
    description: "Name of the captain"
  first mate:
    label: "first mate"
    input: string
    description: "Name of the first mate"
  crew req:
    label: "crew req"
    input: string
    description: "Minimum number of crew members"
  crew act:
    label: "crew act"
    input: string
    description: "Current number of crew members"
  crew wages:
    label: "crew wages"
    input: string
    description: "Coins the average crew member gets per month, might influence their loyalty"
  passengers:
    label: "passengers"
    input: integer
    description: "Current number of passengers"
  soak:
    label: "soak"
    input: integer
    description: "By how much incoming damage is being reduced"
    placeholder: "eg 0 or 3"
  structure:
    label: "structure"
    input: integer
    description: "Works similar to Vigor for characters (current value)"
  structure max:
    label: "structure max"
    input: integer
    description: "Works similar to Vigor for characters (max value)"
  breaks:
    label: "breaks"
    input: integer
    description: "Works similar to Wounds fore characters (current value)"
  breaks max:
    label: "breaks max"
    input: integer
    description: "Works similar to Wounds fore characters (max value)"
  stowage:
    label: "stowage"
    input: string
    description: "Available space on the ship"
    placeholder: "eg 50 (use - for 'enough')"
  cargo:
    label: "cargo"
    input: text
    rows: 20
    description: "Current cargo of the ship"
  notes:
    label: "notes"
    input: text
    rows: 20
    description: "Add special notes here"
  image:
    label: "image"
    input: string
    description: "Image id of the ship"
  weapon name 01:
    label: "weapon name 01"
    input: string
    description: "Name of the weapon"
    placeholder: ""
  weapon range 01:
    label: "weapon range 01"
    input: string
    description: "Range of the weapon"
    placeholder: "eg 1, 2, L, M"
  weapon size 01:
    label: "weapon size 01"
    input: string
    description: "Crew required to operate weapon"
    placeholder: "eg Crew 3, Crew 2+winchers"
  weapon damage 01:
    label: "weapon damage 01"
    input: integer
    description: "Damage of the weapon in d6"
    placeholder: "eg 3 (for 3d6)"
  weapon qualities 01:
    label: "weapon qualities 01"
    input: string
    description: "Qualities of the weapon"
    placeholder: "eg Area, Fearsome 2, Intense, Spread"
  weapon name 02:
    label: "weapon name 02"
    input: string
    description: "Name of the weapon"
    placeholder: ""
  weapon range 02:
    label: "weapon range 02"
    input: string
    description: "Range of the weapon"
    placeholder: "eg 1, 2, L, M"
  weapon size 02:
    label: "weapon size 02"
    input: string
    description: "Crew required to operate weapon"
    placeholder: "eg Crew 3, Crew 2+winchers"
  weapon damage 02:
    label: "weapon damage 02"
    input: integer
    description: "Damage of the weapon in d6"
    placeholder: "eg 3 (for 3d6)"
  weapon qualities 02:
    label: "weapon qualities 02"
    input: string
    description: "Qualities of the weapon"
    placeholder: "eg Area, Fearsome 2, Intense, Spread"
  weapon name 03:
    label: "weapon name 03"
    input: string
    description: "Name of the weapon"
    placeholder: ""
  weapon range 03:
    label: "weapon range 03"
    input: string
    description: "Range of the weapon"
    placeholder: "eg 1, 2, L, M"
  weapon size 03:
    label: "weapon size 03"
    input: string
    description: "Crew required to operate weapon"
    placeholder: "eg Crew 3, Crew 2+winchers"
  weapon damage 03:
    label: "weapon damage 03"
    input: integer
    description: "Damage of the weapon in d6"
    placeholder: "eg 3 (for 3d6)"
  weapon qualities 03:
    label: "weapon qualities 03"
    input: string
    description: "Qualities of the weapon"
    placeholder: "eg Area, Fearsome 2, Intense, Spread"
  weapon name 04:
    label: "weapon name 04"
    input: string
    description: "Name of the weapon"
    placeholder: ""
  weapon range 04:
    label: "weapon range 04"
    input: string
    description: "Range of the weapon"
    placeholder: "eg 1, 2, L, M"
  weapon size 04:
    label: "weapon size 04"
    input: string
    description: "Crew required to operate weapon"
    placeholder: "eg Crew 3, Crew 2+winchers"
  weapon damage 04:
    label: "weapon damage 04"
    input: integer
    description: "Damage of the weapon in d6"
    placeholder: "eg 3 (for 3d6)"
  weapon qualities 04:
    label: "weapon qualities 04"
    input: string
    description: "Qualities of the weapon"
    placeholder: "eg Area, Fearsome 2, Intense, Spread"
  weapon name 05:
    label: "weapon name 05"
    input: string
    description: "Name of the weapon"
    placeholder: ""
  weapon range 05:
    label: "weapon range 05"
    input: string
    description: "Range of the weapon"
    placeholder: "eg 1, 2, L, M"
  weapon size 05:
    label: "weapon size 05"
    input: string
    description: "Crew required to operate weapon"
    placeholder: "eg Crew 3, Crew 2+winchers"
  weapon damage 05:
    label: "weapon damage 05"
    input: integer
    description: "Damage of the weapon in d6"
    placeholder: "eg 3 (for 3d6)"
  weapon qualities 05:
    label: "weapon qualities 05"
    input: string
    description: "Qualities of the weapon"
    placeholder: "eg Area, Fearsome 2, Intense, Spread"
