fields:
  creature agility 01:
    label: "Creature Agility 01"
    input: integer
  creature awareness 01:
    label: "Creature Awareness 01"
    input: integer
  creature brawn 01:
    label: "Creature Brawn 01"
    input: integer
  creature coordination 01:
    label: "Creature Coordination 01"
    input: integer
  creature intelligence 01:
    label: "Creature Intelligence 01"
    input: integer
  creature perception 01:
    label: "Creature perception 01"
    input: integer
  creature willpower 01:
    label: "Creature Willpower 01"
    input: integer
  creature details:
    label: "Details"
    input: text
    rows: 20
  fortitude:
    label: "Fortitude"
    input: integer
  knowledge:
    label: "Knowledge"
    input: integer
  movement:
    label: "Movement"
    input: integer
  senses:
    label: "Senses"
    input: integer
  social:
    label: "Social"
    input: integer
  stress and soak:
    label: "Stress and Soak"
    input: text
    rows: 20
  attacks:
    label: "Attacks"
    input: text
    rows: 20
  special abilities:
    label: "Special Abilities"
    input: text
    rows: 20
