fields:
# base info
  rads:
    label: "rads"
    input: string
    placeholder: ""
  age:
    label: "age"
    input: string
  species:
    label: "species"
    input: string
    placeholder: "eg human"
  species traits:
    label: "species traits"
    input: string
  homeworld:
    label: "homeworld"
    input: string
    placeholder: "eg earth, mars"
# characteristics
  strength:
    label: "strength"
    input: string
  strength max:
    label: "strength max"
    input: string
  dexterity:
    label: "dexterity"
    input: string
  dexterity max:
    label: "dexterity max"
    input: string
  endurance:
    label: "endurance"
    input: string
  endurance max:
    label: "endurance max"
    input: string
  intellect:
    label: "intellect"
    input: string
  intellect max:
    label: "intellect max"
    input: string
  education:
    label: "education"
    input: string
  education max:
    label: "education max"
    input: string
  social:
    label: "social"
    input: string
  social max:
    label: "social max"
    input: string
  psi:
    label: "psi"
    input: string
  psi max:
    label: "psi max"
    input: string
# finances
  pension:
    label: "pension"
    input: string
  debt:
    label: "debt"
    input: string
  cash on hand:
    label: "cash on hand"
    input: string
  monthly ship payments:
    label: "monthly ship payments"
    input: string
  living cost:
    label: "living cost"
    input: string
# other
  npcs:
    label: "npcs"
    input: text
    rows: 10
    placeholder: "list of your allies, enemies etc"
  equipment:
    label: "equipment"
    input: text
    rows: 10
  equipment mass:
    label: "equipment mass"
    input: string
  notes:
    label: "notes"
    input: text
    rows: 10
# study period
  train skill:
    label: "train skill"
    input: string
  train weeks done:
    label: "train weeks done"
    input: string
  train weeks required:
    label: "train weeks required"
    input: string
  train periods done:
    label: "train periods done"
    input: string
# skills
  skill 01:
    label: "skill 01"
    input: string
  skill value 01:
    label: "skill value 01"
    input: string
  skill 02:
    label: "skill 02"
    input: string
  skill value 02:
    label: "skill value 02"
    input: string
  skill 03:
    label: "skill 03"
    input: string
  skill value 03:
    label: "skill value 03"
    input: string
  skill 04:
    label: "skill 04"
    input: string
  skill value 04:
    label: "skill value 04"
    input: string
  skill 05:
    label: "skill 05"
    input: string
  skill value 05:
    label: "skill value 05"
    input: string
  skill 06:
    label: "skill 06"
    input: string
  skill value 06:
    label: "skill value 06"
    input: string
  skill 07:
    label: "skill 07"
    input: string
  skill value 07:
    label: "skill value 07"
    input: string
  skill 08:
    label: "skill 08"
    input: string
  skill value 08:
    label: "skill value 08"
    input: string
  skill 09:
    label: "skill 09"
    input: string
  skill value 09:
    label: "skill value 09"
    input: string
  skill 10:
    label: "skill 10"
    input: string
  skill value 10:
    label: "skill value 10"
    input: string
  skill 11:
    label: "skill 11"
    input: string
  skill value 11:
    label: "skill value 11"
    input: string
  skill 12:
    label: "skill 12"
    input: string
  skill value 12:
    label: "skill value 12"
    input: string
  skill 13:
    label: "skill 13"
    input: string
  skill value 13:
    label: "skill value 13"
    input: string
  skill 14:
    label: "skill 14"
    input: string
  skill value 14:
    label: "skill value 14"
    input: string
  skill 15:
    label: "skill 15"
    input: string
  skill value 15:
    label: "skill value 15"
    input: string
  skill 16:
    label: "skill 16"
    input: string
  skill value 16:
    label: "skill value 16"
    input: string
  skill 17:
    label: "skill 17"
    input: string
  skill value 17:
    label: "skill value 17"
    input: string
  skill 18:
    label: "skill 18"
    input: string
  skill value 18:
    label: "skill value 18"
    input: string
  skill 19:
    label: "skill 19"
    input: string
  skill value 19:
    label: "skill value 19"
    input: string
  skill 20:
    label: "skill 20"
    input: string
  skill value 20:
    label: "skill value 20"
    input: string
  skill 21:
    label: "skill 21"
    input: string
  skill value 21:
    label: "skill value 21"
    input: string
  skill 22:
    label: "skill 22"
    input: string
  skill value 22:
    label: "skill value 22"
    input: string
  skill 23:
    label: "skill 23"
    input: string
  skill value 23:
    label: "skill value 23"
    input: string
  skill 24:
    label: "skill 24"
    input: string
  skill value 24:
    label: "skill value 24"
    input: string
  skill 25:
    label: "skill 25"
    input: string
  skill value 25:
    label: "skill value 25"
    input: string
  skill 26:
    label: "skill 26"
    input: string
  skill value 26:
    label: "skill value 26"
    input: string
  skill 27:
    label: "skill 27"
    input: string
  skill value 27:
    label: "skill value 27"
    input: string
  skill 28:
    label: "skill 28"
    input: string
  skill value 28:
    label: "skill value 28"
    input: string
  skill 29:
    label: "skill 29"
    input: string
  skill value 29:
    label: "skill value 29"
    input: string
  skill 30:
    label: "skill 30"
    input: string
  skill value 30:
    label: "skill value 30"
    input: string
  skill 31:
    label: "skill 31"
    input: string
  skill value 31:
    label: "skill value 31"
    input: string
  skill 32:
    label: "skill 32"
    input: string
  skill value 32:
    label: "skill value 32"
    input: string
  skill 33:
    label: "skill 33"
    input: string
  skill value 33:
    label: "skill value 33"
    input: string
  skill 34:
    label: "skill 34"
    input: string
  skill value 34:
    label: "skill value 34"
    input: string
  skill 35:
    label: "skill 35"
    input: string
  skill value 35:
    label: "skill value 35"
    input: string
  skill 36:
    label: "skill 36"
    input: string
  skill value 36:
    label: "skill value 36"
    input: string
  skill 37:
    label: "skill 37"
    input: string
  skill value 37:
    label: "skill value 37"
    input: string
  skill 38:
    label: "skill 38"
    input: string
  skill value 38:
    label: "skill value 38"
    input: string
  skill 39:
    label: "skill 39"
    input: string
  skill value 39:
    label: "skill value 39"
    input: string
  skill 40:
    label: "skill 40"
    input: string
  skill value 40:
    label: "skill value 40"
    input: string
  skill 41:
    label: "skill 41"
    input: string
  skill value 41:
    label: "skill value 41"
    input: string
  skill 42:
    label: "skill 42"
    input: string
  skill value 42:
    label: "skill value 42"
    input: string
  skill 43:
    label: "skill 43"
    input: string
  skill value 43:
    label: "skill value 43"
    input: string
  skill 44:
    label: "skill 44"
    input: string
  skill value 44:
    label: "skill value 44"
    input: string
  skill 45:
    label: "skill 45"
    input: string
  skill value 45:
    label: "skill value 45"
    input: string
  skill 46:
    label: "skill 46"
    input: string
  skill value 46:
    label: "skill value 46"
    input: string
  skill 47:
    label: "skill 47"
    input: string
  skill value 47:
    label: "skill value 47"
    input: string
  skill 48:
    label: "skill 48"
    input: string
  skill value 48:
    label: "skill value 48"
    input: string
  skill 49:
    label: "skill 49"
    input: string
  skill value 49:
    label: "skill value 49"
    input: string
  skill 50:
    label: "skill 50"
    input: string
  skill value 50:
    label: "skill value 50"
    input: string
  skill 51:
    label: "skill 51"
    input: string
  skill value 51:
    label: "skill value 51"
    input: string
  skill 52:
    label: "skill 52"
    input: string
  skill value 52:
    label: "skill value 52"
    input: string
  skill 53:
    label: "skill 53"
    input: string
  skill value 53:
    label: "skill value 53"
    input: string
  skill 54:
    label: "skill 54"
    input: string
  skill value 54:
    label: "skill value 54"
    input: string
  skill 55:
    label: "skill 55"
    input: string
  skill value 55:
    label: "skill value 55"
    input: string
  skill 56:
    label: "skill 56"
    input: string
  skill value 56:
    label: "skill value 56"
    input: string
  skill 57:
    label: "skill 57"
    input: string
  skill value 57:
    label: "skill value 57"
    input: string
  skill 58:
    label: "skill 58"
    input: string
  skill value 58:
    label: "skill value 58"
    input: string
  skill 59:
    label: "skill 59"
    input: string
  skill value 59:
    label: "skill value 59"
    input: string
  skill 60:
    label: "skill 60"
    input: string
  skill value 60:
    label: "skill value 60"
    input: string
  skill 61:
    label: "skill 61"
    input: string
  skill value 61:
    label: "skill value 61"
    input: string
  skill 62:
    label: "skill 62"
    input: string
  skill value 62:
    label: "skill value 62"
    input: string
  skill 63:
    label: "skill 63"
    input: string
  skill value 63:
    label: "skill value 63"
    input: string
  skill 64:
    label: "skill 64"
    input: string
  skill value 64:
    label: "skill value 64"
    input: string
  skill 65:
    label: "skill 65"
    input: string
  skill value 65:
    label: "skill value 65"
    input: string
  skill 66:
    label: "skill 66"
    input: string
  skill value 66:
    label: "skill value 66"
    input: string
  skill 67:
    label: "skill 67"
    input: string
  skill value 67:
    label: "skill value 67"
    input: string
  skill 68:
    label: "skill 68"
    input: string
  skill value 68:
    label: "skill value 68"
    input: string
  skill 69:
    label: "skill 69"
    input: string
  skill value 69:
    label: "skill value 69"
    input: string
  skill 70:
    label: "skill 70"
    input: string
  skill value 70:
    label: "skill value 70"
    input: string
# armour
  armour type 01:
    label: "armour type 01"
    input: string
  armour rad 01:
    label: "armour rad 01"
    input: string
  armour protection 01:
    label: "armour protection 01"
    input: string
  armour kg 01:
    label: "armour kg 01"
    input: string
  armour options 01:
    label: "armour options 01"
    input: string
  armour type 02:
    label: "armour type 02"
    input: string
  armour rad 02:
    label: "armour rad 02"
    input: string
  armour protection 02:
    label: "armour protection 02"
    input: string
  armour kg 02:
    label: "armour kg 02"
    input: string
  armour options 02:
    label: "armour options 02"
    input: string
  armour type 03:
    label: "armour type 03"
    input: string
  armour rad 03:
    label: "armour rad 03"
    input: string
  armour protection 03:
    label: "armour protection 03"
    input: string
  armour kg 03:
    label: "armour kg 03"
    input: string
  armour options 03:
    label: "armour options 03"
    input: string
# weapons
  weapon 01:
    label: "weapon 01"
    input: string
  weapon tl 01:
    label: "weapon tl 01"
    input: string
  weapon range 01:
    label: "weapon range 01"
    input: string
  weapon dmg 01:
    label: "weapon dmg 01"
    input: string
  weapon kg 01:
    label: "weapon kg 01"
    input: string
  weapon magazine 01:
    label: "weapon magazine 01"
    input: string
  weapon traits 01:
    label: "weapon traits 01"
    input: string
  weapon 02:
    label: "weapon 02"
    input: string
  weapon tl 02:
    label: "weapon tl 02"
    input: string
  weapon range 02:
    label: "weapon range 02"
    input: string
  weapon dmg 02:
    label: "weapon dmg 02"
    input: string
  weapon kg 02:
    label: "weapon kg 02"
    input: string
  weapon magazine 02:
    label: "weapon magazine 02"
    input: string
  weapon traits 02:
    label: "weapon traits 02"
    input: string
  weapon 03:
    label: "weapon 03"
    input: string
  weapon tl 03:
    label: "weapon tl 03"
    input: string
  weapon range 03:
    label: "weapon range 03"
    input: string
  weapon dmg 03:
    label: "weapon dmg 03"
    input: string
  weapon kg 03:
    label: "weapon kg 03"
    input: string
  weapon magazine 03:
    label: "weapon magazine 03"
    input: string
  weapon traits 03:
    label: "weapon traits 03"
    input: string
  weapon 04:
    label: "weapon 04"
    input: string
  weapon tl 04:
    label: "weapon tl 04"
    input: string
  weapon range 04:
    label: "weapon range 04"
    input: string
  weapon dmg 04:
    label: "weapon dmg 04"
    input: string
  weapon kg 04:
    label: "weapon kg 04"
    input: string
  weapon magazine 04:
    label: "weapon magazine 04"
    input: string
  weapon traits 04:
    label: "weapon traits 04"
    input: string
  weapon 05:
    label: "weapon 05"
    input: string
  weapon tl 05:
    label: "weapon tl 05"
    input: string
  weapon range 05:
    label: "weapon range 05"
    input: string
  weapon dmg 05:
    label: "weapon dmg 05"
    input: string
  weapon kg 05:
    label: "weapon kg 05"
    input: string
  weapon magazine 05:
    label: "weapon magazine 05"
    input: string
  weapon traits 05:
    label: "weapon traits 05"
    input: string
  weapon 06:
    label: "weapon 06"
    input: string
  weapon tl 06:
    label: "weapon tl 06"
    input: string
  weapon range 06:
    label: "weapon range 06"
    input: string
  weapon dmg 06:
    label: "weapon dmg 06"
    input: string
  weapon kg 06:
    label: "weapon kg 06"
    input: string
  weapon magazine 06:
    label: "weapon magazine 06"
    input: string
  weapon traits 06:
    label: "weapon traits 06"
    input: string
  weapon 07:
    label: "weapon 07"
    input: string
  weapon tl 07:
    label: "weapon tl 07"
    input: string
  weapon range 07:
    label: "weapon range 07"
    input: string
  weapon dmg 07:
    label: "weapon dmg 07"
    input: string
  weapon kg 07:
    label: "weapon kg 07"
    input: string
  weapon magazine 07:
    label: "weapon magazine 07"
    input: string
  weapon traits 07:
    label: "weapon traits 07"
    input: string
  weapon 08:
    label: "weapon 08"
    input: string
  weapon tl 08:
    label: "weapon tl 08"
    input: string
  weapon range 08:
    label: "weapon range 08"
    input: string
  weapon dmg 08:
    label: "weapon dmg 08"
    input: string
  weapon kg 08:
    label: "weapon kg 08"
    input: string
  weapon magazine 08:
    label: "weapon magazine 08"
    input: string
  weapon traits 08:
    label: "weapon traits 08"
    input: string
  weapon 09:
    label: "weapon 09"
    input: string
  weapon tl 09:
    label: "weapon tl 09"
    input: string
  weapon range 09:
    label: "weapon range 09"
    input: string
  weapon dmg 09:
    label: "weapon dmg 09"
    input: string
  weapon kg 09:
    label: "weapon kg 09"
    input: string
  weapon magazine 09:
    label: "weapon magazine 09"
    input: string
  weapon traits 09:
    label: "weapon traits 09"
    input: string
  weapon 10:
    label: "weapon 10"
    input: string
  weapon tl 10:
    label: "weapon tl 10"
    input: string
  weapon range 10:
    label: "weapon range 10"
    input: string
  weapon dmg 10:
    label: "weapon dmg 10"
    input: string
  weapon kg 10:
    label: "weapon kg 10"
    input: string
  weapon magazine 10:
    label: "weapon magazine 10"
    input: string
  weapon traits 10:
    label: "weapon traits 10"
    input: string
# augments
  augment type 01:
    label: "augment type 01"
    input: string
  augment tl 01:
    label: "augment tl 01"
    input: string
  augment improvement 01:
    label: "augment improvement 01"
    input: string
  augment type 02:
    label: "augment type 02"
    input: string
  augment tl 02:
    label: "augment tl 02"
    input: string
  augment improvement 02:
    label: "augment improvement 02"
    input: string
  augment type 03:
    label: "augment type 03"
    input: string
  augment tl 03:
    label: "augment tl 03"
    input: string
  augment improvement 03:
    label: "augment improvement 03"
    input: string
  augment type 04:
    label: "augment type 04"
    input: string
  augment tl 04:
    label: "augment tl 04"
    input: string
  augment improvement 04:
    label: "augment improvement 04"
    input: string
  augment type 05:
    label: "augment type 05"
    input: string
  augment tl 05:
    label: "augment tl 05"
    input: string
  augment improvement 05:
    label: "augment improvement 05"
    input: string
  augment type 06:
    label: "augment type 06"
    input: string
  augment tl 06:
    label: "augment tl 06"
    input: string
  augment improvement 06:
    label: "augment improvement 06"
    input: string
  augment type 07:
    label: "augment type 07"
    input: string
  augment tl 07:
    label: "augment tl 07"
    input: string
  augment improvement 07:
    label: "augment improvement 07"
    input: string
  augment type 08:
    label: "augment type 08"
    input: string
  augment tl 08:
    label: "augment tl 08"
    input: string
  augment improvement 08:
    label: "augment improvement 08"
    input: string
  augment type 09:
    label: "augment type 09"
    input: string
  augment tl 09:
    label: "augment tl 09"
    input: string
  augment improvement 09:
    label: "augment improvement 09"
    input: string
  augment type 10:
    label: "augment type 10"
    input: string
  augment tl 10:
    label: "augment tl 10"
    input: string
  augment improvement 10:
    label: "augment improvement 10"
    input: string
  augment type 11:
    label: "augment type 11"
    input: string
  augment tl 11:
    label: "augment tl 11"
    input: string
  augment improvement 11:
    label: "augment improvement 11"
    input: string
  augment type 12:
    label: "augment type 12"
    input: string
  augment tl 12:
    label: "augment tl 12"
    input: string
  augment improvement 12:
    label: "augment improvement 12"
    input: string
  augment type 13:
    label: "augment type 13"
    input: string
  augment tl 13:
    label: "augment tl 13"
    input: string
  augment improvement 13:
    label: "augment improvement 13"
    input: string
  augment type 14:
    label: "augment type 14"
    input: string
  augment tl 14:
    label: "augment tl 14"
    input: string
  augment improvement 14:
    label: "augment improvement 14"
    input: string
  augment type 15:
    label: "augment type 15"
    input: string
  augment tl 15:
    label: "augment tl 15"
    input: string
  augment improvement 15:
    label: "augment improvement 15"
    input: string
