fields:
  image:
    label: "Image"
    input: integer
  desc:
    label: "Desc"
    input: string
  armor:
    label: "Armor"
    input: string
  strength:
    label: "Strength"
    required: true
    input: integer
  endurance:
    label: "Endurance"
    required: true
    input: integer
  agility:
    label: "Agility"
    required: true
    input: integer
  intelligence:
    label: "Intelligence"
    required: true
    input: integer
  willpower:
    label: "Willpower"
    required: true
    input: integer
  perception:
    label: "Perception"
    required: true
    input: integer
  personality:
    label: "Personality"
    required: true
    input: integer
  luck:
    label: "Luck"
    required: true
    input: integer
  hp curr:
    label: "hp curr"
    required: true
    input: integer
  wound threshold:
    label: "wound threshold"
    required: true
    input: integer
  magicka curr:
    label: "magicka curr"
    input: integer
  stamina curr:
    label: "stamina curr"
    input: integer
  init rating:
    label: "init rating"
    input: integer
  action curr:
    label: "action curr"
    input: integer
  speed:
    label: "Speed"
    input: integer
  size:
    label: "Size"
    required: true
    input: select
    options:
      puny: puny
      tiny: tiny
      small: small
      standard: standard
      large: large
  sk_combat:
    label: "SK Combat"
    input: integer
  sk_magic:
    label: "SK Magic"
    input: integer
  sk_evade:
    label: "SK Evade"
    input: integer
  sk_observe:
    label: "SK Observe"
    input: integer
  sk_stealth:
    label: "SK Stealth"
    input: integer
  sk_knowledge:
    label: "SK Knowledge"
    input: integer
  sk_social:
    label: "SK Social"
    input: integer
  sk_physical:
    label: "SK Physical"
    input: integer
  equipment:
    label: "Equipment"
    input: text
    rows: 20
  abilities:
    label: "Abilities"
    input: text
    rows: 20
  talents:
    label: "Talents"
    input: text
    rows: 20
  notes:
    label: "Notes"
    input: text
    rows: 20
