fields:
  designation:
    label: "designation"
    input: string
  service date:
    label: "service date"
    input: string
  space frame:
    label: "space frame"
    input: string
  mission profile:
    label: "mission profile"
    input: string
  refit:
    label: "refit"
    input: string
  engines:
    label: "engines"
    input: integer
  engines breaches:
    label: "engines breaches"
    input: integer
  computers:
    label: "computers"
    input: integer
  computers breaches:
    label: "computers breaches"
    input: integer
  weapons:
    label: "weapons"
    input: integer
  weapons breaches:
    label: "weapons breaches"
    input: integer
  structure:
    label: "structure"
    input: integer
  structure breaches:
    label: "structure breaches"
    input: integer
  sensors:
    label: "sensors"
    input: integer
  sensors breaches:
    label: "sensors breaches"
    input: integer
  communications:
    label: "communications"
    input: integer
  communications breaches:
    label: "communications breaches"
    input: integer
  command:
    label: "command"
    input: integer
  security:
    label: "security"
    input: integer
  science:
    label: "science"
    input: integer
  conn:
    label: "conn"
    input: integer
  engineering:
    label: "engineering"
    input: integer
  medicine:
    label: "medicine"
    input: integer
  talents:
    label: "talents"
    input: text
    rows: 10
  scale:
    label: "scale"
    input: integer
  power current:
    label: "power current"
    input: integer
  power max:
    label: "power max"
    input: integer
  shields current:
    label: "shields current"
    input: integer
  shields max:
    label: "shields max"
    input: integer
  launch bay:
    label: "launch bay"
    input: text
    rows: 10
  crew support max:
    label: "crew support max"
    input: integer
  crew support current:
    label: "crew support current"
    input: integer
  notes: 
    label: "notes"
    description: "Notes"
    input: text
    rows: 10
  resistance:
    label: "resistance"
    input: integer
    description: "Equal to Scale plus Talent modifications"
  trait:
    label: "trait"
    placeholder: "eg Prototype, Legacy Vessel, Renowned, Long-Serving"
    input: string
  weapon nametype 01:
    label: "weapon nametype 01"
    input: string
  weapon skill 01:
    label: "weapon skill 01"
    input: integer
  weapon qualities 01:
    label: "weapon qualities 01"
    input: string
  weapon nametype 02:
    label: "weapon nametype 02"
    input: string
  weapon skill 02:
    label: "weapon skill 02"
    input: integer
  weapon qualities 02:
    label: "weapon qualities 02"
    input: string
  weapon nametype 03:
    label: "weapon nametype 03"
    input: string
  weapon skill 03:
    label: "weapon skill 03"
    input: integer
  weapon qualities 03:
    label: "weapon qualities 03"
    input: string
  weapon nametype 04:
    label: "weapon nametype 04"
    input: string
  weapon skill 04:
    label: "weapon skill 04"
    input: integer
  weapon qualities 04:
    label: "weapon qualities 04"
    input: string
  weapon nametype 05:
    label: "weapon nametype 05"
    input: string
  weapon skill 05:
    label: "weapon skill 05"
    input: integer
  weapon qualities 05:
    label: "weapon qualities 05"
    input: string
  weapon nametype 06:
    label: "weapon nametype 06"
    input: string
  weapon skill 06:
    label: "weapon skill 06"
    input: integer
  weapon qualities 06:
    label: "weapon qualities 06"
    input: string
  weapon nametype 07:
    label: "weapon nametype 07"
    input: string
  weapon skill 07:
    label: "weapon skill 07"
    input: integer
  weapon qualities 07:
    label: "weapon qualities 07"
    input: string
  weapon nametype 08:
    label: "weapon nametype 08"
    input: string
  weapon skill 08:
    label: "weapon skill 08"
    input: integer
  weapon qualities 08:
    label: "weapon qualities 08"
    input: string
  weapon nametype 09:
    label: "weapon nametype 09"
    input: string
  weapon skill 09:
    label: "weapon skill 09"
    input: integer
  weapon qualities 09:
    label: "weapon qualities 09"
    input: string
  weapon nametype 10:
    label: "weapon nametype 10"
    input: string
  weapon skill 10:
    label: "weapon skill 10"
    input: integer
  weapon qualities 10:
    label: "weapon qualities 10"
    input: string
