fields:
  age:
    label: "Age"
    required: true
    input: integer
  affiliation:
    label: "Affiliation"
    required: true
    input: string
  height:
    label: "Height"
    input: string
  weight:
    label: "Weight"
    input: string
  strength value:
    label: "Strength Value"
    input: integer
    min: 0
    max: 10
  body value:
    label: "Body Value"
    input: integer
    min: 0
    max: 10
  dexterity value:
    label: "Dexterity Value"
    input: integer
    min: 0
    max: 10
  reflexes value:
    label: "Reflexes Value"
    input: integer
    min: 0
    max: 10
  intelligence value:
    label: "Intelligence Value"
    input: integer
    min: 0
    max: 10
  willpower value:
    label: "Willpower Value"
    input: integer
    min: 0
    max: 10
  charisma value:
    label: "Charisma Value"
    input: integer
    min: 0
    max: 10
  edge value:
    label: "Edge Value"
    input: integer
    min: 0
    max: 10
  social standing value:
    label: "Social Standing Value"
    input: integer
    min: 0
    max: 10
  strength max:
    label: "Strength Max"
    input: integer
  body max:
    label: "Body Max"
    input: integer
  dexterity max:
    label: "Dexterity Max"
    input: integer
  reflexes max:
    label: "Reflexes Max"
    input: integer
  intelligence max:
    label: "Intelligence Max"
    input: integer
  willpower max:
    label: "Willpower Max"
    input: integer
  charisma max:
    label: "Charisma Max"
    input: integer
  edge max:
    label: "Edge Max"
    input: integer
  social standing max:
    label: "Social Standing Max"
    input: integer
  skill name 01:
    label: "Skill Name 01"
    integer: string
  skill bonus 01:
    label: "Skill Bonus 01"
    integer: integer
  skill name 02:
    label: "Skill Name 02"
    integer: string
  skill bonus 02:
    label: "Skill Bonus 02"
    integer: integer
  skill name 03:
    label: "Skill Name 03"
    integer: string
  skill bonus 03:
    label: "Skill Bonus 03"
    integer: integer
  skill name 04:
    label: "Skill Name 04"
    integer: string
  skill bonus 04:
    label: "Skill Bonus 04"
    integer: integer
  skill name 05:
    label: "Skill Name 05"
    integer: string
  skill bonus 05:
    label: "Skill Bonus 05"
    integer: integer
  skill name 06:
    label: "Skill Name 06"
    integer: string
  skill bonus 06:
    label: "Skill Bonus 06"
    integer: integer
  skill name 07:
    label: "Skill Name 07"
    integer: string
  skill bonus 07:
    label: "Skill Bonus 07"
    integer: integer
  skill name 08:
    label: "Skill Name 08"
    integer: string
  skill bonus 08:
    label: "Skill Bonus 08"
    integer: integer
  skill name 09:
    label: "Skill Name 09"
    integer: string
  skill bonus 09:
    label: "Skill Bonus 09"
    integer: integer
  skill name 10:
    label: "Skill Name 10"
    integer: string
  skill bonus 10:
    label: "Skill Bonus 10"
    integer: integer
  skill name 11:
    label: "Skill Name 11"
    integer: string
  skill bonus 11:
    label: "Skill Bonus 11"
    integer: integer
  skill name 12:
    label: "Skill Name 12"
    integer: string
  skill bonus 12:
    label: "Skill Bonus 12"
    integer: integer
  skill name 13:
    label: "Skill Name 13"
    integer: string
  skill bonus 13:
    label: "Skill Bonus 13"
    integer: integer
  skill name 14:
    label: "Skill Name 14"
    integer: string
  skill bonus 14:
    label: "Skill Bonus 14"
    integer: integer
  skill name 15:
    label: "Skill Name 15"
    integer: string
  skill bonus 15:
    label: "Skill Bonus 15"
    integer: integer
  skill name 16:
    label: "Skill Name 16"
    integer: string
  skill bonus 16:
    label: "Skill Bonus 16"
    integer: integer
  skill name 17:
    label: "Skill Name 17"
    integer: string
  skill bonus 17:
    label: "Skill Bonus 17"
    integer: integer
  skill name 18:
    label: "Skill Name 18"
    integer: string
  skill bonus 18:
    label: "Skill Bonus 18"
    integer: integer
  skill name 19:
    label: "Skill Name 19"
    integer: string
  skill bonus 19:
    label: "Skill Bonus 19"
    integer: integer
  skill name 20:
    label: "Skill Name 20"
    integer: string
  skill bonus 20:
    label: "Skill Bonus 20"
    integer: integer
  skill name 21:
    label: "Skill Name 21"
    integer: string
  skill bonus 21:
    label: "Skill Bonus 21"
    integer: integer
  skill name 22:
    label: "Skill Name 22"
    integer: string
  skill bonus 22:
    label: "Skill Bonus 22"
    integer: integer
  skill name 23:
    label: "Skill Name 23"
    integer: string
  skill bonus 23:
    label: "Skill Bonus 23"
    integer: integer
  skill name 24:
    label: "Skill Name 24"
    integer: string
  skill bonus 24:
    label: "Skill Bonus 24"
    integer: integer
  skill name 25:
    label: "Skill Name 25"
    integer: string
  skill bonus 25:
    label: "Skill Bonus 25"
    integer: integer
  skill name 26:
    label: "Skill Name 26"
    integer: string
  skill bonus 26:
    label: "Skill Bonus 26"
    integer: integer
  skill name 27:
    label: "Skill Name 27"
    integer: string
  skill bonus 27:
    label: "Skill Bonus 27"
    integer: integer
  skill name 28:
    label: "Skill Name 28"
    integer: string
  skill bonus 28:
    label: "Skill Bonus 28"
    integer: integer
  skill name 29:
    label: "Skill Name 29"
    integer: string
  skill bonus 29:
    label: "Skill Bonus 29"
    integer: integer
  skill name 30:
    label: "Skill Name 30"
    integer: string
  skill bonus 30:
    label: "Skill Bonus 30"
    integer: integer
  skill name 31:
    label: "Skill Name 31"
    integer: string
  skill bonus 31:
    label: "Skill Bonus 31"
    integer: integer
  skill name 32:
    label: "Skill Name 32"
    integer: string
  skill bonus 32:
    label: "Skill Bonus 32"
    integer: integer
  skill name 33:
    label: "Skill Name 33"
    integer: string
  skill bonus 33:
    label: "Skill Bonus 33"
    integer: integer
  skill name 34:
    label: "Skill Name 34"
    integer: string
  skill bonus 34:
    label: "Skill Bonus 34"
    integer: integer
  skill name 35:
    label: "Skill Name 35"
    integer: string
  skill bonus 35:
    label: "Skill Bonus 35"
    integer: integer
  skill name 36:
    label: "Skill Name 36"
    integer: string
  skill bonus 36:
    label: "Skill Bonus 36"
    integer: integer
  skill name 37:
    label: "Skill Name 37"
    integer: string
  skill bonus 37:
    label: "Skill Bonus 37"
    integer: integer
  skill name 38:
    label: "Skill Name 38"
    integer: string
  skill bonus 38:
    label: "Skill Bonus 38"
    integer: integer
  skill name 39:
    label: "Skill Name 39"
    integer: string
  skill bonus 39:
    label: "Skill Bonus 39"
    integer: integer
  skill name 40:
    label: "Skill Name 40"
    integer: string
  skill bonus 40:
    label: "Skill Bonus 40"
    integer: integer
  skill name 41:
    label: "Skill Name 41"
    integer: string
  skill bonus 41:
    label: "Skill Bonus 41"
    integer: integer
  skill name 42:
    label: "Skill Name 42"
    integer: string
  skill bonus 42:
    label: "Skill Bonus 42"
    integer: integer
  skill name 43:
    label: "Skill Name 43"
    integer: string
  skill bonus 43:
    label: "Skill Bonus 43"
    integer: integer
  skill name 44:
    label: "Skill Name 44"
    integer: string
  skill bonus 44:
    label: "Skill Bonus 44"
    integer: integer
  skill name 45:
    label: "Skill Name 45"
    integer: string
  skill bonus 45:
    label: "Skill Bonus 45"
    integer: integer
  skill name 46:
    label: "Skill Name 46"
    integer: string
  skill bonus 46:
    label: "Skill Bonus 46"
    integer: integer
  skill name 47:
    label: "Skill Name 47"
    integer: string
  skill bonus 47:
    label: "Skill Bonus 47"
    integer: integer
  skill name 48:
    label: "Skill Name 48"
    integer: string
  skill bonus 48:
    label: "Skill Bonus 48"
    integer: integer
  skill name 49:
    label: "Skill Name 49"
    integer: string
  skill bonus 49:
    label: "Skill Bonus 49"
    integer: integer
  skill name 50:
    label: "Skill Name 50"
    integer: string
  skill bonus 50:
    label: "Skill Bonus 50"
    integer: integer
  trait 01:
    label: "Trait 01"
    integer: string
  trait 02:
    label: "Trait 02"
    integer: string
  trait 03:
    label: "Trait 03"
    integer: string
  trait 04:
    label: "Trait 04"
    integer: string
  trait 05:
    label: "Trait 05"
    integer: string
  trait 06:
    label: "Trait 06"
    integer: string
  trait 07:
    label: "Trait 07"
    integer: string
  trait 08:
    label: "Trait 08"
    integer: string
  trait 09:
    label: "Trait 09"
    integer: string
  trait 10:
    label: "Trait 10"
    integer: string
  trait 11:
    label: "Trait 11"
    integer: string
  trait 12:
    label: "Trait 12"
    integer: string
  trait 13:
    label: "Trait 13"
    integer: string
  trait 14:
    label: "Trait 14"
    integer: string
  trait 15:
    label: "Trait 15"
    integer: string
  trait 16:
    label: "Trait 16"
    integer: string
  trait 17:
    label: "Trait 17"
    integer: string
  trait 18:
    label: "Trait 18"
    integer: string
  trait 19:
    label: "Trait 19"
    integer: string
  trait 20:
    label: "Trait 20"
    integer: string
  armor a name:
    label: "armor a name"
    input: string
  armor a m:
    label: "armor a m"
    input: integer
  armor a b:
    label: "armor a b"
    input: integer
  armor a e:
    label: "armor a e"
    input: integer
  armor a x:
    label: "armor a x"
    input: integer
  armor b name:
    label: "armor b name"
    input: string
  armor b m:
    label: "armor b m"
    input: integer
  armor b b:
    label: "armor b b"
    input: integer
  armor b e:
    label: "armor b e"
    input: integer
  armor b x:
    label: "armor b x"
    input: integer
  armor c name:
    label: "armor c name"
    input: string
  armor c m:
    label: "armor c m"
    input: integer
  armor c b:
    label: "armor c b"
    input: integer
  armor c e:
    label: "armor c e"
    input: integer
  armor c x:
    label: "armor c x"
    input: integer
  armor d name:
    label: "armor d name"
    input: string
  armor d m:
    label: "armor d m"
    input: integer
  armor d b:
    label: "armor d b"
    input: integer
  armor d e:
    label: "armor d e"
    input: integer
  armor d x:
    label: "armor d x"
    input: integer
  notes:
    label: "Notes"
    input: text
    rows: 20
  equipment:
    label: "Equipment"
    input: text
    rows: 20
  xp:
    label: "XP"
    input: integer
  movement w:
    label: "Movement w"
    input: integer
  movement r:
    label: "Movement r"
    input: integer
  movement s:
    label: "Movement s"
    input: integer
  weapon name 01:
    label: "weapon name 01"
    input: string
  weapon ap dmg 01:
    label: "weapon ap dmg 01"
    input: string
  weapon type 01:
    label: "weapon type 01"
    input: select
    options:
      melee: melee
      ballistic: ballistic
      energy: energy
      explosive: explosive
  weapon range 01:
    label: "weapon range 01"
    input: string
  weapon shots 01:
    label: "weapon shots 01"
    input: integer
  weapon notes 01:
    label: "weapon notes 01"
    input: string
  weapon name 02:
    label: "weapon name 02"
    input: string
  weapon ap dmg 02:
    label: "weapon ap dmg 02"
    input: string
  weapon type 02:
    label: "weapon type 02"
    input: select
    options:
      melee: melee
      ballistic: ballistic
      energy: energy
      explosive: explosive
  weapon range 02:
    label: "weapon range 02"
    input: string
  weapon shots 02:
    label: "weapon shots 02"
    input: integer
  weapon notes 02:
    label: "weapon notes 02"
    input: string
  weapon name 03:
    label: "weapon name 03"
    input: string
  weapon ap dmg 03:
    label: "weapon ap dmg 03"
    input: string
  weapon type 03:
    label: "weapon type 03"
    input: select
    options:
      melee: melee
      ballistic: ballistic
      energy: energy
      explosive: explosive
  weapon range 03:
    label: "weapon range 03"
    input: string
  weapon shots 03:
    label: "weapon shots 03"
    input: integer
  weapon notes 03:
    label: "weapon notes 03"
    input: string
  weapon name 04:
    label: "weapon name 04"
    input: string
  weapon ap dmg 04:
    label: "weapon ap dmg 04"
    input: string
  weapon type 04:
    label: "weapon type 04"
    input: select
    options:
      melee: melee
      ballistic: ballistic
      energy: energy
      explosive: explosive
  weapon range 04:
    label: "weapon range 04"
    input: string
  weapon shots 04:
    label: "weapon shots 04"
    input: integer
  weapon notes 04:
    label: "weapon notes 04"
    input: string
  weapon name 05:
    label: "weapon name 05"
    input: string
  weapon ap dmg 05:
    label: "weapon ap dmg 05"
    input: string
  weapon type 05:
    label: "weapon type 05"
    input: select
    options:
      melee: melee
      ballistic: ballistic
      energy: energy
      explosive: explosive
  weapon range 05:
    label: "weapon range 05"
    input: string
  weapon shots 05:
    label: "weapon shots 05"
    input: integer
  weapon notes 05:
    label: "weapon notes 05"
    input: string
  hl head:
    label: "hl head"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl chest:
    label: "hl chest"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl rarm:
    label: "hl rarm"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl larm:
    label: "hl larm"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl abdomen:
    label: "hl abdomen"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl rleg:
    label: "hl rleg"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl lleg:
    label: "hl lleg"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl rhand:
    label: "hl rhand"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl lhand:
    label: "hl lhand"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl rfoot:
    label: "hl rfoot"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  hl lfoot:
    label: "hl lfoot"
    input: select
    options:
      n: n
      a: a
      b: b
      c: c
      d: d
  fatigue:
    label: "fatigue"
    input: integer
  wounds 1:
    label: "wounds 1"
    input: integer
  wounds 2:
    label: "wounds 2"
    input: integer
  wounds 4:
    label: "wounds 4"
    input: integer
  wounds 8:
    label: "wounds 8"
    input: integer
  wounds 16:
    label: "wounds 16"
    input: integer
  wounds head:
    label: "wounds head"
    input: integer
  wounds chest:
    label: "wounds chest"
    input: integer
  wounds rarm:
    label: "wounds rarm"
    input: integer
  wounds larm:
    label: "wounds larm"
    input: integer
  wounds abdomen:
    label: "wounds abdomen"
    input: integer
  wounds rleg:
    label: "wounds rleg"
    input: integer
  wounds lleg:
    label: "wounds lleg"
    input: integer
  wounds rhand:
    label: "wounds rhand"
    input: integer
  wounds lhand:
    label: "wounds lhand"
    input: integer
  wounds rfoot:
    label: "wounds rfoot"
    input: integer
  wounds lfoot:
    label: "wounds lfoot"
    input: integer
