fields:
  first truth:
    label: "First Truth"
    input: string
    required: true
  second truth:
    label: "Second Truth"
    input: string
    required: true
  archetype:
    label: "Archetype"
    input: select
    required: true
    options:
      Assassin: Assassin
      Commander: Commander
      Courier: Courier
      Duelist: Duelist
      Entrepreneur: Entrepreneur
      Explorer: Explorer
      Guide: Guide
      Hunter: Hunter
      Inventor: Inventor
      Miscreant: Miscreant
      Scholar: Scholar
      Scout: Scout
      Sharpshooter: Sharpshooter
  description:
    label: "description"
    input: text
    rows: 20
  fight:
    label: "Fight"
    input: integer
    required: true
  move:
    label: "Move"
    input: integer
    required: true
  study:
    label: "Study"
    input: integer
    required: true
  survive:
    label: "Survive"
    input: integer
    required: true
  talk:
    label: "Talk"
    input: integer
    required: true
  tinker:
    label: "Tinker"
    input: integer
    required: true
  boldly:
    label: "Boldly"
    input: integer
    required: true
  carefully:
    label: "Carefully"
    input: integer
    required: true
  cleverly:
    label: "Cleverly"
    input: integer
    required: true
  forcfully:
    label: "Forcefully"
    input: integer
    required: true
  quietly:
    label: "Quietly"
    input: integer
    required: true
  swiftly:
    label: "Swiftly"
    input: integer
    required: true
  void points:
    label: "Void Points"
    input: integer
  void point max:
    label: "Void Point Max"
    input: integer
  stress:
    label: "Stress"
    input: integer
  stress max:
    label: "Stress Max"
    input: integer
  momentum:
    label: "Momentum"
    input: integer
  contacts:
    label: "Contacts"
    input: text
    rows: 10
  talents:
    label: "Talents"
    input: text
    rows: 10
  focus name 01:
    label: "Focus Name 01"
    input: string
  focus score 01:
    label: "Focus Score 01"
    input: integer
  focus name 02:
    label: "Focus Name 02"
    input: string
  focus score 02:
    label: "Focus Score 02"
    input: integer
  focus name 03:
    label: "Focus Name 03"
    input: string
  focus score 03:
    label: "Focus Score 03"
    input: integer
  focus name 04:
    label: "Focus Name 04"
    input: string
  focus score 04:
    label: "Focus Score 04"
    input: integer
  focus name 05:
    label: "Focus Name 05"
    input: string
  focus score 05:
    label: "Focus Score 05"
    input: integer
  focus name 06:
    label: "Focus Name 06"
    input: string
  focus score 06:
    label: "Focus Score 06"
    input: integer
  focus name 07:
    label: "Focus Name 07"
    input: string
  focus score 07:
    label: "Focus Score 07"
    input: integer
  focus name 08:
    label: "Focus Name 08"
    input: string
  focus score 08:
    label: "Focus Score 08"
    input: integer
  focus name 09:
    label: "Focus Name 09"
    input: string
  focus score 09:
    label: "Focus Score 09"
    input: integer
  focus name 10:
    label: "Focus Name 10"
    input: string
  focus score 10:
    label: "Focus Score 10"
    input: integer
  notes:
    label: "Notes"
    input: text
    rows: 20
  powers:
    label: "Powers"
    input: text
    rows: 10
  belongings:
    label: "Belongings"
    input: text
    rows: 20
  xp:
    label: "XP"
    input: integer
